// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package smart.proxies;

public class Asset implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject assetMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Smart.Asset";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		IIH_Id("IIH_Id"),
		Nom("Nom"),
		isElec("isElec"),
		isGaz("isGaz"),
		isEau("isEau"),
		isAir("isAir"),
		isVisited("isVisited"),
		HasChildren("HasChildren"),
		ConsoTotalElec("ConsoTotalElec"),
		ConsoTotalGaz("ConsoTotalGaz"),
		ConsoTotalEau("ConsoTotalEau"),
		ConsoTotalAir("ConsoTotalAir"),
		ConsoTotalElecPrev("ConsoTotalElecPrev"),
		ConsoTotalGazPrev("ConsoTotalGazPrev"),
		ConsoTotalEauPrev("ConsoTotalEauPrev"),
		ConsoTotalAirPrev("ConsoTotalAirPrev"),
		IPEElec("IPEElec"),
		IPEGaz("IPEGaz"),
		IPEEau("IPEEau"),
		IPEAir("IPEAir"),
		IPEElecKg("IPEElecKg"),
		IPEGazKg("IPEGazKg"),
		IPEEauKg("IPEEauKg"),
		IPEAirKg("IPEAirKg"),
		ProdTotal("ProdTotal"),
		ProdTotalPrev("ProdTotalPrev"),
		ProdTotalKg("ProdTotalKg"),
		ProdTotalPrevKg("ProdTotalPrevKg"),
		Asset_Parent("Smart.Asset_Parent"),
		Asset_Level("Smart.Asset_Level");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Asset(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Asset(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject assetMendixObject)
	{
		if (assetMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, assetMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.assetMendixObject = assetMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static smart.proxies.Asset initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new smart.proxies.Asset(context, mendixObject);
	}

	public static smart.proxies.Asset load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return smart.proxies.Asset.initialize(context, mendixObject);
	}

	public static java.util.List<smart.proxies.Asset> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> smart.proxies.Asset.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of IIH_Id
	 */
	public final java.lang.String getIIH_Id()
	{
		return getIIH_Id(getContext());
	}

	/**
	 * @param context
	 * @return value of IIH_Id
	 */
	public final java.lang.String getIIH_Id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IIH_Id.toString());
	}

	/**
	 * Set value of IIH_Id
	 * @param iih_id
	 */
	public final void setIIH_Id(java.lang.String iih_id)
	{
		setIIH_Id(getContext(), iih_id);
	}

	/**
	 * Set value of IIH_Id
	 * @param context
	 * @param iih_id
	 */
	public final void setIIH_Id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String iih_id)
	{
		getMendixObject().setValue(context, MemberNames.IIH_Id.toString(), iih_id);
	}

	/**
	 * @return value of Nom
	 */
	public final java.lang.String getNom()
	{
		return getNom(getContext());
	}

	/**
	 * @param context
	 * @return value of Nom
	 */
	public final java.lang.String getNom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Nom.toString());
	}

	/**
	 * Set value of Nom
	 * @param nom
	 */
	public final void setNom(java.lang.String nom)
	{
		setNom(getContext(), nom);
	}

	/**
	 * Set value of Nom
	 * @param context
	 * @param nom
	 */
	public final void setNom(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nom)
	{
		getMendixObject().setValue(context, MemberNames.Nom.toString(), nom);
	}

	/**
	 * @return value of isElec
	 */
	public final java.lang.Boolean getisElec()
	{
		return getisElec(getContext());
	}

	/**
	 * @param context
	 * @return value of isElec
	 */
	public final java.lang.Boolean getisElec(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isElec.toString());
	}

	/**
	 * Set value of isElec
	 * @param iselec
	 */
	public final void setisElec(java.lang.Boolean iselec)
	{
		setisElec(getContext(), iselec);
	}

	/**
	 * Set value of isElec
	 * @param context
	 * @param iselec
	 */
	public final void setisElec(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean iselec)
	{
		getMendixObject().setValue(context, MemberNames.isElec.toString(), iselec);
	}

	/**
	 * @return value of isGaz
	 */
	public final java.lang.Boolean getisGaz()
	{
		return getisGaz(getContext());
	}

	/**
	 * @param context
	 * @return value of isGaz
	 */
	public final java.lang.Boolean getisGaz(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isGaz.toString());
	}

	/**
	 * Set value of isGaz
	 * @param isgaz
	 */
	public final void setisGaz(java.lang.Boolean isgaz)
	{
		setisGaz(getContext(), isgaz);
	}

	/**
	 * Set value of isGaz
	 * @param context
	 * @param isgaz
	 */
	public final void setisGaz(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isgaz)
	{
		getMendixObject().setValue(context, MemberNames.isGaz.toString(), isgaz);
	}

	/**
	 * @return value of isEau
	 */
	public final java.lang.Boolean getisEau()
	{
		return getisEau(getContext());
	}

	/**
	 * @param context
	 * @return value of isEau
	 */
	public final java.lang.Boolean getisEau(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isEau.toString());
	}

	/**
	 * Set value of isEau
	 * @param iseau
	 */
	public final void setisEau(java.lang.Boolean iseau)
	{
		setisEau(getContext(), iseau);
	}

	/**
	 * Set value of isEau
	 * @param context
	 * @param iseau
	 */
	public final void setisEau(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean iseau)
	{
		getMendixObject().setValue(context, MemberNames.isEau.toString(), iseau);
	}

	/**
	 * @return value of isAir
	 */
	public final java.lang.Boolean getisAir()
	{
		return getisAir(getContext());
	}

	/**
	 * @param context
	 * @return value of isAir
	 */
	public final java.lang.Boolean getisAir(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isAir.toString());
	}

	/**
	 * Set value of isAir
	 * @param isair
	 */
	public final void setisAir(java.lang.Boolean isair)
	{
		setisAir(getContext(), isair);
	}

	/**
	 * Set value of isAir
	 * @param context
	 * @param isair
	 */
	public final void setisAir(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isair)
	{
		getMendixObject().setValue(context, MemberNames.isAir.toString(), isair);
	}

	/**
	 * @return value of isVisited
	 */
	public final java.lang.Boolean getisVisited()
	{
		return getisVisited(getContext());
	}

	/**
	 * @param context
	 * @return value of isVisited
	 */
	public final java.lang.Boolean getisVisited(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isVisited.toString());
	}

	/**
	 * Set value of isVisited
	 * @param isvisited
	 */
	public final void setisVisited(java.lang.Boolean isvisited)
	{
		setisVisited(getContext(), isvisited);
	}

	/**
	 * Set value of isVisited
	 * @param context
	 * @param isvisited
	 */
	public final void setisVisited(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isvisited)
	{
		getMendixObject().setValue(context, MemberNames.isVisited.toString(), isvisited);
	}

	/**
	 * @return value of HasChildren
	 */
	public final java.lang.Boolean getHasChildren()
	{
		return getHasChildren(getContext());
	}

	/**
	 * @param context
	 * @return value of HasChildren
	 */
	public final java.lang.Boolean getHasChildren(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasChildren.toString());
	}

	/**
	 * Set value of HasChildren
	 * @param haschildren
	 */
	public final void setHasChildren(java.lang.Boolean haschildren)
	{
		setHasChildren(getContext(), haschildren);
	}

	/**
	 * Set value of HasChildren
	 * @param context
	 * @param haschildren
	 */
	public final void setHasChildren(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean haschildren)
	{
		getMendixObject().setValue(context, MemberNames.HasChildren.toString(), haschildren);
	}

	/**
	 * @return value of ConsoTotalElec
	 */
	public final java.math.BigDecimal getConsoTotalElec()
	{
		return getConsoTotalElec(getContext());
	}

	/**
	 * @param context
	 * @return value of ConsoTotalElec
	 */
	public final java.math.BigDecimal getConsoTotalElec(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ConsoTotalElec.toString());
	}

	/**
	 * Set value of ConsoTotalElec
	 * @param consototalelec
	 */
	public final void setConsoTotalElec(java.math.BigDecimal consototalelec)
	{
		setConsoTotalElec(getContext(), consototalelec);
	}

	/**
	 * Set value of ConsoTotalElec
	 * @param context
	 * @param consototalelec
	 */
	public final void setConsoTotalElec(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal consototalelec)
	{
		getMendixObject().setValue(context, MemberNames.ConsoTotalElec.toString(), consototalelec);
	}

	/**
	 * @return value of ConsoTotalGaz
	 */
	public final java.math.BigDecimal getConsoTotalGaz()
	{
		return getConsoTotalGaz(getContext());
	}

	/**
	 * @param context
	 * @return value of ConsoTotalGaz
	 */
	public final java.math.BigDecimal getConsoTotalGaz(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ConsoTotalGaz.toString());
	}

	/**
	 * Set value of ConsoTotalGaz
	 * @param consototalgaz
	 */
	public final void setConsoTotalGaz(java.math.BigDecimal consototalgaz)
	{
		setConsoTotalGaz(getContext(), consototalgaz);
	}

	/**
	 * Set value of ConsoTotalGaz
	 * @param context
	 * @param consototalgaz
	 */
	public final void setConsoTotalGaz(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal consototalgaz)
	{
		getMendixObject().setValue(context, MemberNames.ConsoTotalGaz.toString(), consototalgaz);
	}

	/**
	 * @return value of ConsoTotalEau
	 */
	public final java.math.BigDecimal getConsoTotalEau()
	{
		return getConsoTotalEau(getContext());
	}

	/**
	 * @param context
	 * @return value of ConsoTotalEau
	 */
	public final java.math.BigDecimal getConsoTotalEau(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ConsoTotalEau.toString());
	}

	/**
	 * Set value of ConsoTotalEau
	 * @param consototaleau
	 */
	public final void setConsoTotalEau(java.math.BigDecimal consototaleau)
	{
		setConsoTotalEau(getContext(), consototaleau);
	}

	/**
	 * Set value of ConsoTotalEau
	 * @param context
	 * @param consototaleau
	 */
	public final void setConsoTotalEau(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal consototaleau)
	{
		getMendixObject().setValue(context, MemberNames.ConsoTotalEau.toString(), consototaleau);
	}

	/**
	 * @return value of ConsoTotalAir
	 */
	public final java.math.BigDecimal getConsoTotalAir()
	{
		return getConsoTotalAir(getContext());
	}

	/**
	 * @param context
	 * @return value of ConsoTotalAir
	 */
	public final java.math.BigDecimal getConsoTotalAir(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ConsoTotalAir.toString());
	}

	/**
	 * Set value of ConsoTotalAir
	 * @param consototalair
	 */
	public final void setConsoTotalAir(java.math.BigDecimal consototalair)
	{
		setConsoTotalAir(getContext(), consototalair);
	}

	/**
	 * Set value of ConsoTotalAir
	 * @param context
	 * @param consototalair
	 */
	public final void setConsoTotalAir(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal consototalair)
	{
		getMendixObject().setValue(context, MemberNames.ConsoTotalAir.toString(), consototalair);
	}

	/**
	 * @return value of ConsoTotalElecPrev
	 */
	public final java.math.BigDecimal getConsoTotalElecPrev()
	{
		return getConsoTotalElecPrev(getContext());
	}

	/**
	 * @param context
	 * @return value of ConsoTotalElecPrev
	 */
	public final java.math.BigDecimal getConsoTotalElecPrev(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ConsoTotalElecPrev.toString());
	}

	/**
	 * Set value of ConsoTotalElecPrev
	 * @param consototalelecprev
	 */
	public final void setConsoTotalElecPrev(java.math.BigDecimal consototalelecprev)
	{
		setConsoTotalElecPrev(getContext(), consototalelecprev);
	}

	/**
	 * Set value of ConsoTotalElecPrev
	 * @param context
	 * @param consototalelecprev
	 */
	public final void setConsoTotalElecPrev(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal consototalelecprev)
	{
		getMendixObject().setValue(context, MemberNames.ConsoTotalElecPrev.toString(), consototalelecprev);
	}

	/**
	 * @return value of ConsoTotalGazPrev
	 */
	public final java.math.BigDecimal getConsoTotalGazPrev()
	{
		return getConsoTotalGazPrev(getContext());
	}

	/**
	 * @param context
	 * @return value of ConsoTotalGazPrev
	 */
	public final java.math.BigDecimal getConsoTotalGazPrev(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ConsoTotalGazPrev.toString());
	}

	/**
	 * Set value of ConsoTotalGazPrev
	 * @param consototalgazprev
	 */
	public final void setConsoTotalGazPrev(java.math.BigDecimal consototalgazprev)
	{
		setConsoTotalGazPrev(getContext(), consototalgazprev);
	}

	/**
	 * Set value of ConsoTotalGazPrev
	 * @param context
	 * @param consototalgazprev
	 */
	public final void setConsoTotalGazPrev(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal consototalgazprev)
	{
		getMendixObject().setValue(context, MemberNames.ConsoTotalGazPrev.toString(), consototalgazprev);
	}

	/**
	 * @return value of ConsoTotalEauPrev
	 */
	public final java.math.BigDecimal getConsoTotalEauPrev()
	{
		return getConsoTotalEauPrev(getContext());
	}

	/**
	 * @param context
	 * @return value of ConsoTotalEauPrev
	 */
	public final java.math.BigDecimal getConsoTotalEauPrev(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ConsoTotalEauPrev.toString());
	}

	/**
	 * Set value of ConsoTotalEauPrev
	 * @param consototaleauprev
	 */
	public final void setConsoTotalEauPrev(java.math.BigDecimal consototaleauprev)
	{
		setConsoTotalEauPrev(getContext(), consototaleauprev);
	}

	/**
	 * Set value of ConsoTotalEauPrev
	 * @param context
	 * @param consototaleauprev
	 */
	public final void setConsoTotalEauPrev(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal consototaleauprev)
	{
		getMendixObject().setValue(context, MemberNames.ConsoTotalEauPrev.toString(), consototaleauprev);
	}

	/**
	 * @return value of ConsoTotalAirPrev
	 */
	public final java.math.BigDecimal getConsoTotalAirPrev()
	{
		return getConsoTotalAirPrev(getContext());
	}

	/**
	 * @param context
	 * @return value of ConsoTotalAirPrev
	 */
	public final java.math.BigDecimal getConsoTotalAirPrev(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ConsoTotalAirPrev.toString());
	}

	/**
	 * Set value of ConsoTotalAirPrev
	 * @param consototalairprev
	 */
	public final void setConsoTotalAirPrev(java.math.BigDecimal consototalairprev)
	{
		setConsoTotalAirPrev(getContext(), consototalairprev);
	}

	/**
	 * Set value of ConsoTotalAirPrev
	 * @param context
	 * @param consototalairprev
	 */
	public final void setConsoTotalAirPrev(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal consototalairprev)
	{
		getMendixObject().setValue(context, MemberNames.ConsoTotalAirPrev.toString(), consototalairprev);
	}

	/**
	 * @return value of IPEElec
	 */
	public final java.math.BigDecimal getIPEElec()
	{
		return getIPEElec(getContext());
	}

	/**
	 * @param context
	 * @return value of IPEElec
	 */
	public final java.math.BigDecimal getIPEElec(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.IPEElec.toString());
	}

	/**
	 * Set value of IPEElec
	 * @param ipeelec
	 */
	public final void setIPEElec(java.math.BigDecimal ipeelec)
	{
		setIPEElec(getContext(), ipeelec);
	}

	/**
	 * Set value of IPEElec
	 * @param context
	 * @param ipeelec
	 */
	public final void setIPEElec(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal ipeelec)
	{
		getMendixObject().setValue(context, MemberNames.IPEElec.toString(), ipeelec);
	}

	/**
	 * @return value of IPEGaz
	 */
	public final java.math.BigDecimal getIPEGaz()
	{
		return getIPEGaz(getContext());
	}

	/**
	 * @param context
	 * @return value of IPEGaz
	 */
	public final java.math.BigDecimal getIPEGaz(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.IPEGaz.toString());
	}

	/**
	 * Set value of IPEGaz
	 * @param ipegaz
	 */
	public final void setIPEGaz(java.math.BigDecimal ipegaz)
	{
		setIPEGaz(getContext(), ipegaz);
	}

	/**
	 * Set value of IPEGaz
	 * @param context
	 * @param ipegaz
	 */
	public final void setIPEGaz(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal ipegaz)
	{
		getMendixObject().setValue(context, MemberNames.IPEGaz.toString(), ipegaz);
	}

	/**
	 * @return value of IPEEau
	 */
	public final java.math.BigDecimal getIPEEau()
	{
		return getIPEEau(getContext());
	}

	/**
	 * @param context
	 * @return value of IPEEau
	 */
	public final java.math.BigDecimal getIPEEau(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.IPEEau.toString());
	}

	/**
	 * Set value of IPEEau
	 * @param ipeeau
	 */
	public final void setIPEEau(java.math.BigDecimal ipeeau)
	{
		setIPEEau(getContext(), ipeeau);
	}

	/**
	 * Set value of IPEEau
	 * @param context
	 * @param ipeeau
	 */
	public final void setIPEEau(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal ipeeau)
	{
		getMendixObject().setValue(context, MemberNames.IPEEau.toString(), ipeeau);
	}

	/**
	 * @return value of IPEAir
	 */
	public final java.math.BigDecimal getIPEAir()
	{
		return getIPEAir(getContext());
	}

	/**
	 * @param context
	 * @return value of IPEAir
	 */
	public final java.math.BigDecimal getIPEAir(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.IPEAir.toString());
	}

	/**
	 * Set value of IPEAir
	 * @param ipeair
	 */
	public final void setIPEAir(java.math.BigDecimal ipeair)
	{
		setIPEAir(getContext(), ipeair);
	}

	/**
	 * Set value of IPEAir
	 * @param context
	 * @param ipeair
	 */
	public final void setIPEAir(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal ipeair)
	{
		getMendixObject().setValue(context, MemberNames.IPEAir.toString(), ipeair);
	}

	/**
	 * @return value of IPEElecKg
	 */
	public final java.math.BigDecimal getIPEElecKg()
	{
		return getIPEElecKg(getContext());
	}

	/**
	 * @param context
	 * @return value of IPEElecKg
	 */
	public final java.math.BigDecimal getIPEElecKg(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.IPEElecKg.toString());
	}

	/**
	 * Set value of IPEElecKg
	 * @param ipeeleckg
	 */
	public final void setIPEElecKg(java.math.BigDecimal ipeeleckg)
	{
		setIPEElecKg(getContext(), ipeeleckg);
	}

	/**
	 * Set value of IPEElecKg
	 * @param context
	 * @param ipeeleckg
	 */
	public final void setIPEElecKg(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal ipeeleckg)
	{
		getMendixObject().setValue(context, MemberNames.IPEElecKg.toString(), ipeeleckg);
	}

	/**
	 * @return value of IPEGazKg
	 */
	public final java.math.BigDecimal getIPEGazKg()
	{
		return getIPEGazKg(getContext());
	}

	/**
	 * @param context
	 * @return value of IPEGazKg
	 */
	public final java.math.BigDecimal getIPEGazKg(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.IPEGazKg.toString());
	}

	/**
	 * Set value of IPEGazKg
	 * @param ipegazkg
	 */
	public final void setIPEGazKg(java.math.BigDecimal ipegazkg)
	{
		setIPEGazKg(getContext(), ipegazkg);
	}

	/**
	 * Set value of IPEGazKg
	 * @param context
	 * @param ipegazkg
	 */
	public final void setIPEGazKg(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal ipegazkg)
	{
		getMendixObject().setValue(context, MemberNames.IPEGazKg.toString(), ipegazkg);
	}

	/**
	 * @return value of IPEEauKg
	 */
	public final java.math.BigDecimal getIPEEauKg()
	{
		return getIPEEauKg(getContext());
	}

	/**
	 * @param context
	 * @return value of IPEEauKg
	 */
	public final java.math.BigDecimal getIPEEauKg(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.IPEEauKg.toString());
	}

	/**
	 * Set value of IPEEauKg
	 * @param ipeeaukg
	 */
	public final void setIPEEauKg(java.math.BigDecimal ipeeaukg)
	{
		setIPEEauKg(getContext(), ipeeaukg);
	}

	/**
	 * Set value of IPEEauKg
	 * @param context
	 * @param ipeeaukg
	 */
	public final void setIPEEauKg(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal ipeeaukg)
	{
		getMendixObject().setValue(context, MemberNames.IPEEauKg.toString(), ipeeaukg);
	}

	/**
	 * @return value of IPEAirKg
	 */
	public final java.math.BigDecimal getIPEAirKg()
	{
		return getIPEAirKg(getContext());
	}

	/**
	 * @param context
	 * @return value of IPEAirKg
	 */
	public final java.math.BigDecimal getIPEAirKg(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.IPEAirKg.toString());
	}

	/**
	 * Set value of IPEAirKg
	 * @param ipeairkg
	 */
	public final void setIPEAirKg(java.math.BigDecimal ipeairkg)
	{
		setIPEAirKg(getContext(), ipeairkg);
	}

	/**
	 * Set value of IPEAirKg
	 * @param context
	 * @param ipeairkg
	 */
	public final void setIPEAirKg(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal ipeairkg)
	{
		getMendixObject().setValue(context, MemberNames.IPEAirKg.toString(), ipeairkg);
	}

	/**
	 * @return value of ProdTotal
	 */
	public final java.math.BigDecimal getProdTotal()
	{
		return getProdTotal(getContext());
	}

	/**
	 * @param context
	 * @return value of ProdTotal
	 */
	public final java.math.BigDecimal getProdTotal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ProdTotal.toString());
	}

	/**
	 * Set value of ProdTotal
	 * @param prodtotal
	 */
	public final void setProdTotal(java.math.BigDecimal prodtotal)
	{
		setProdTotal(getContext(), prodtotal);
	}

	/**
	 * Set value of ProdTotal
	 * @param context
	 * @param prodtotal
	 */
	public final void setProdTotal(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal prodtotal)
	{
		getMendixObject().setValue(context, MemberNames.ProdTotal.toString(), prodtotal);
	}

	/**
	 * @return value of ProdTotalPrev
	 */
	public final java.math.BigDecimal getProdTotalPrev()
	{
		return getProdTotalPrev(getContext());
	}

	/**
	 * @param context
	 * @return value of ProdTotalPrev
	 */
	public final java.math.BigDecimal getProdTotalPrev(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ProdTotalPrev.toString());
	}

	/**
	 * Set value of ProdTotalPrev
	 * @param prodtotalprev
	 */
	public final void setProdTotalPrev(java.math.BigDecimal prodtotalprev)
	{
		setProdTotalPrev(getContext(), prodtotalprev);
	}

	/**
	 * Set value of ProdTotalPrev
	 * @param context
	 * @param prodtotalprev
	 */
	public final void setProdTotalPrev(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal prodtotalprev)
	{
		getMendixObject().setValue(context, MemberNames.ProdTotalPrev.toString(), prodtotalprev);
	}

	/**
	 * @return value of ProdTotalKg
	 */
	public final java.math.BigDecimal getProdTotalKg()
	{
		return getProdTotalKg(getContext());
	}

	/**
	 * @param context
	 * @return value of ProdTotalKg
	 */
	public final java.math.BigDecimal getProdTotalKg(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ProdTotalKg.toString());
	}

	/**
	 * Set value of ProdTotalKg
	 * @param prodtotalkg
	 */
	public final void setProdTotalKg(java.math.BigDecimal prodtotalkg)
	{
		setProdTotalKg(getContext(), prodtotalkg);
	}

	/**
	 * Set value of ProdTotalKg
	 * @param context
	 * @param prodtotalkg
	 */
	public final void setProdTotalKg(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal prodtotalkg)
	{
		getMendixObject().setValue(context, MemberNames.ProdTotalKg.toString(), prodtotalkg);
	}

	/**
	 * @return value of ProdTotalPrevKg
	 */
	public final java.math.BigDecimal getProdTotalPrevKg()
	{
		return getProdTotalPrevKg(getContext());
	}

	/**
	 * @param context
	 * @return value of ProdTotalPrevKg
	 */
	public final java.math.BigDecimal getProdTotalPrevKg(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ProdTotalPrevKg.toString());
	}

	/**
	 * Set value of ProdTotalPrevKg
	 * @param prodtotalprevkg
	 */
	public final void setProdTotalPrevKg(java.math.BigDecimal prodtotalprevkg)
	{
		setProdTotalPrevKg(getContext(), prodtotalprevkg);
	}

	/**
	 * Set value of ProdTotalPrevKg
	 * @param context
	 * @param prodtotalprevkg
	 */
	public final void setProdTotalPrevKg(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal prodtotalprevkg)
	{
		getMendixObject().setValue(context, MemberNames.ProdTotalPrevKg.toString(), prodtotalprevkg);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Asset_Parent
	 */
	public final smart.proxies.Asset getAsset_Parent() throws com.mendix.core.CoreException
	{
		return getAsset_Parent(getContext());
	}

	/**
	 * @param context
	 * @return value of Asset_Parent
	 * @throws com.mendix.core.CoreException
	 */
	public final smart.proxies.Asset getAsset_Parent(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		smart.proxies.Asset result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Asset_Parent.toString());
		if (identifier != null) {
			result = smart.proxies.Asset.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Asset_Parent
	 * @param asset_parent
	 */
	public final void setAsset_Parent(smart.proxies.Asset asset_parent)
	{
		setAsset_Parent(getContext(), asset_parent);
	}

	/**
	 * Set value of Asset_Parent
	 * @param context
	 * @param asset_parent
	 */
	public final void setAsset_Parent(com.mendix.systemwideinterfaces.core.IContext context, smart.proxies.Asset asset_parent)
	{
		if (asset_parent == null) {
			getMendixObject().setValue(context, MemberNames.Asset_Parent.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Asset_Parent.toString(), asset_parent.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Asset_Level
	 */
	public final smart.proxies.Level getAsset_Level() throws com.mendix.core.CoreException
	{
		return getAsset_Level(getContext());
	}

	/**
	 * @param context
	 * @return value of Asset_Level
	 * @throws com.mendix.core.CoreException
	 */
	public final smart.proxies.Level getAsset_Level(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		smart.proxies.Level result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Asset_Level.toString());
		if (identifier != null) {
			result = smart.proxies.Level.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Asset_Level
	 * @param asset_level
	 */
	public final void setAsset_Level(smart.proxies.Level asset_level)
	{
		setAsset_Level(getContext(), asset_level);
	}

	/**
	 * Set value of Asset_Level
	 * @param context
	 * @param asset_level
	 */
	public final void setAsset_Level(com.mendix.systemwideinterfaces.core.IContext context, smart.proxies.Level asset_level)
	{
		if (asset_level == null) {
			getMendixObject().setValue(context, MemberNames.Asset_Level.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Asset_Level.toString(), asset_level.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return assetMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final smart.proxies.Asset that = (smart.proxies.Asset) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
