/**
 * This file was generated from FadTable.xml
 * WARNING: All changes made to this file will be overwritten
 * @author Mendix Widgets Framework Team
 */
import { CSSProperties } from "react";
import { ListValue, ListAttributeValue } from "mendix";
import { Big } from "big.js";

export type SelectedEnergyTypeEnum = "Elec" | "Gaz" | "Eau" | "Air";

export type LoadingStrategyEnum = "loadAll" | "pagination" | "lazyLoad";

export interface FadTableContainerProps {
    name: string;
    class: string;
    style?: CSSProperties;
    tabIndex?: number;
    dsGridData: ListValue;
    useFlexibleHierarchy: boolean;
    attrLeafNodeName: ListAttributeValue<string>;
    attrMachineName?: ListAttributeValue<string>;
    attrAtelierName?: ListAttributeValue<string>;
    attrSecteurName?: ListAttributeValue<string>;
    hierarchyLevel1Name: string;
    hierarchyLevel1Attr?: ListAttributeValue<string>;
    hierarchyLevel1Required: boolean;
    hierarchyLevel2Name: string;
    hierarchyLevel2Attr?: ListAttributeValue<string>;
    hierarchyLevel2Required: boolean;
    hierarchyLevel3Name: string;
    hierarchyLevel3Attr?: ListAttributeValue<string>;
    hierarchyLevel3Required: boolean;
    hierarchyLevel4Name: string;
    hierarchyLevel4Attr?: ListAttributeValue<string>;
    hierarchyLevel4Required: boolean;
    hierarchyLevel5Name: string;
    hierarchyLevel5Attr?: ListAttributeValue<string>;
    hierarchyLevel5Required: boolean;
    hierarchyLevel6Name: string;
    hierarchyLevel6Attr?: ListAttributeValue<string>;
    hierarchyLevel6Required: boolean;
    hierarchyLevel7Name: string;
    hierarchyLevel7Attr?: ListAttributeValue<string>;
    hierarchyLevel7Required: boolean;
    hierarchyLevel8Name: string;
    hierarchyLevel8Attr?: ListAttributeValue<string>;
    hierarchyLevel8Required: boolean;
    hierarchyLevel9Name: string;
    hierarchyLevel9Attr?: ListAttributeValue<string>;
    hierarchyLevel9Required: boolean;
    hierarchyLevel10Name: string;
    hierarchyLevel10Attr?: ListAttributeValue<string>;
    hierarchyLevel10Required: boolean;
    hierarchyLevel1Color: string;
    hierarchyLevel2Color: string;
    hierarchyLevel3Color: string;
    hierarchyLevel4Color: string;
    hierarchyLevel5Color: string;
    hierarchyLevel6Color: string;
    hierarchyLevel7Color: string;
    hierarchyLevel8Color: string;
    hierarchyLevel9Color: string;
    hierarchyLevel10Color: string;
    attrTypeEnergie: ListAttributeValue<string>;
    attrJanValue: ListAttributeValue<Big>;
    attrFebValue: ListAttributeValue<Big>;
    attrMarValue: ListAttributeValue<Big>;
    attrAprValue: ListAttributeValue<Big>;
    attrMayValue: ListAttributeValue<Big>;
    attrJunValue: ListAttributeValue<Big>;
    attrJulValue: ListAttributeValue<Big>;
    attrAugValue: ListAttributeValue<Big>;
    attrSepValue: ListAttributeValue<Big>;
    attrOctValue: ListAttributeValue<Big>;
    attrNovValue: ListAttributeValue<Big>;
    attrDecValue: ListAttributeValue<Big>;
    attrTotalYearValue: ListAttributeValue<Big>;
    selectedEnergyType: SelectedEnergyTypeEnum;
    showTotals: boolean;
    enableExport: boolean;
    enableFilter: boolean;
    enableSort: boolean;
    loadingStrategy: LoadingStrategyEnum;
    pageSize: number;
    enableComparison: boolean;
    attrPrevJanValue?: ListAttributeValue<Big>;
    attrPrevFebValue?: ListAttributeValue<Big>;
    attrPrevMarValue?: ListAttributeValue<Big>;
    attrPrevAprValue?: ListAttributeValue<Big>;
    attrPrevMayValue?: ListAttributeValue<Big>;
    attrPrevJunValue?: ListAttributeValue<Big>;
    attrPrevJulValue?: ListAttributeValue<Big>;
    attrPrevAugValue?: ListAttributeValue<Big>;
    attrPrevSepValue?: ListAttributeValue<Big>;
    attrPrevOctValue?: ListAttributeValue<Big>;
    attrPrevNovValue?: ListAttributeValue<Big>;
    attrPrevDecValue?: ListAttributeValue<Big>;
    attrPrevTotalYearValue?: ListAttributeValue<Big>;
    theme: string;
}

export interface FadTablePreviewProps {
    /**
     * @deprecated Deprecated since version 9.18.0. Please use class property instead.
     */
    className: string;
    class: string;
    style: string;
    styleObject?: CSSProperties;
    readOnly: boolean;
    renderMode: "design" | "xray" | "structure";
    translate: (text: string) => string;
    dsGridData: {} | { caption: string } | { type: string } | null;
    useFlexibleHierarchy: boolean;
    attrLeafNodeName: string;
    attrMachineName: string;
    attrAtelierName: string;
    attrSecteurName: string;
    hierarchyLevel1Name: string;
    hierarchyLevel1Attr: string;
    hierarchyLevel1Required: boolean;
    hierarchyLevel2Name: string;
    hierarchyLevel2Attr: string;
    hierarchyLevel2Required: boolean;
    hierarchyLevel3Name: string;
    hierarchyLevel3Attr: string;
    hierarchyLevel3Required: boolean;
    hierarchyLevel4Name: string;
    hierarchyLevel4Attr: string;
    hierarchyLevel4Required: boolean;
    hierarchyLevel5Name: string;
    hierarchyLevel5Attr: string;
    hierarchyLevel5Required: boolean;
    hierarchyLevel6Name: string;
    hierarchyLevel6Attr: string;
    hierarchyLevel6Required: boolean;
    hierarchyLevel7Name: string;
    hierarchyLevel7Attr: string;
    hierarchyLevel7Required: boolean;
    hierarchyLevel8Name: string;
    hierarchyLevel8Attr: string;
    hierarchyLevel8Required: boolean;
    hierarchyLevel9Name: string;
    hierarchyLevel9Attr: string;
    hierarchyLevel9Required: boolean;
    hierarchyLevel10Name: string;
    hierarchyLevel10Attr: string;
    hierarchyLevel10Required: boolean;
    hierarchyLevel1Color: string;
    hierarchyLevel2Color: string;
    hierarchyLevel3Color: string;
    hierarchyLevel4Color: string;
    hierarchyLevel5Color: string;
    hierarchyLevel6Color: string;
    hierarchyLevel7Color: string;
    hierarchyLevel8Color: string;
    hierarchyLevel9Color: string;
    hierarchyLevel10Color: string;
    attrTypeEnergie: string;
    attrJanValue: string;
    attrFebValue: string;
    attrMarValue: string;
    attrAprValue: string;
    attrMayValue: string;
    attrJunValue: string;
    attrJulValue: string;
    attrAugValue: string;
    attrSepValue: string;
    attrOctValue: string;
    attrNovValue: string;
    attrDecValue: string;
    attrTotalYearValue: string;
    selectedEnergyType: SelectedEnergyTypeEnum;
    showTotals: boolean;
    enableExport: boolean;
    enableFilter: boolean;
    enableSort: boolean;
    loadingStrategy: LoadingStrategyEnum;
    pageSize: number | null;
    enableComparison: boolean;
    attrPrevJanValue: string;
    attrPrevFebValue: string;
    attrPrevMarValue: string;
    attrPrevAprValue: string;
    attrPrevMayValue: string;
    attrPrevJunValue: string;
    attrPrevJulValue: string;
    attrPrevAugValue: string;
    attrPrevSepValue: string;
    attrPrevOctValue: string;
    attrPrevNovValue: string;
    attrPrevDecValue: string;
    attrPrevTotalYearValue: string;
    theme: string;
}
