import { StyleSheet } from "@react-pdf/renderer";

// Styles pour le PDF
export const pdfStyles = StyleSheet.create({
    page: {
        paddingTop: 35,
        paddingBottom: 65,
        paddingHorizontal: 35,
        fontFamily: "Barlow",
        backgroundColor: "#ffffff",
    },
    coverPage: {
        position: "relative",
        width: "100%",
        height: "100%",
        backgroundColor: "#1e3a8a",
        alignItems: "center",
        justifyContent: "center",
    },
    coverContent: {
        textAlign: "center",
        padding: 40,
    },
    logo: {
        maxWidth: 100,
        maxHeight: 100,
        marginBottom: 30,
        objectFit: "contain", // Maintient les proportions
    },
    reportTitleText: {
        fontSize: 36,
        marginBottom: 15,
        fontWeight: "bold",
        color: "#ffffff",
    },
    subtitleText: {
        fontSize: 20,
        marginBottom: 20,
        color: "#e0e0e0",
    },
    generationDateText: {
        fontSize: 14,
        color: "#a0a0a0",
        position: "absolute",
        bottom: 40,
        left: 40,
    },
    sectionTitle: {
        fontSize: 22,
        fontWeight: "bold",
        color: "#1e3a8a",
        marginBottom: 15,
        marginTop: 20,
        borderBottomWidth: 2,
        borderBottomColor: "#3b82f6",
        paddingBottom: 5,
    },
    subsectionTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#2563eb",
        marginBottom: 12,
        marginTop: 15,
    },
    table: {
        display: "flex",
        width: "auto",
        borderStyle: "solid",
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 4,
        overflow: "hidden",
        marginTop: 10,
        marginBottom: 20,
    },
    tableRow: {
        margin: "auto",
        flexDirection: "row",
        borderStyle: "solid",
        borderWidth: 0,
        borderBottomWidth: 1,
        borderColor: '#e5e7eb',
    },
    tableHeader: {
        backgroundColor: "#f3f4f6",
        fontWeight: "bold",
    },
    tableCol: {
        width: "20%", // Default for 5 columns, may be overridden for Machine specific layouts
        borderStyle: "solid",
        borderWidth: 0,
        borderRightWidth: 1,
        borderColor: '#e5e7eb',
        padding: 8,
    },
    tableColNarrow: { // Used for first column for Secteur/Atelier
        width: "20%", 
        borderStyle: "solid",
        borderWidth: 0,
        borderRightWidth: 1,
        borderColor: '#e5e7eb',
        padding: 8,
    },
    tableColWide: { // Used for first column for Machine
        width: "35%", 
        borderStyle: "solid",
        borderWidth: 0,
        borderRightWidth: 1,
        borderColor: '#e5e7eb',
        padding: 8,
    },
    tableColDynamic: { // For data columns when first is wide (100-35)/4 = 16.25%
        width: "16.25%",
        borderStyle: "solid",
        borderWidth: 0,
        borderRightWidth: 1,
        borderColor: '#e5e7eb',
        padding: 8,
    },
    tableColIPE: { // Default for IPE table (4 columns)
        width: "25%", 
        borderStyle: "solid",
        borderWidth: 0,
        borderRightWidth: 1,
        borderColor: '#e5e7eb',
        padding: 8,
    },
    tableColIPEWideName: { // For IPE table, Machine name column (35%)
        width: "35%",
        borderStyle: "solid",
        borderWidth: 0,
        borderRightWidth: 1,
        borderColor: '#e5e7eb',
        padding: 8,
    },
    tableColIPEDynamic: { // For IPE table data columns when name is wide (100-35)/3 = ~21.67%
        width: "21.66%", // Using 21.66 to prevent overflow with 3 cols (21.66*3 + 35 = 99.98)
        borderStyle: "solid",
        borderWidth: 0,
        borderRightWidth: 1,
        borderColor: '#e5e7eb',
        padding: 8,
    },
    tableCell: {
        fontSize: 9,
        padding: 2,
        color: "#374151",
        overflow: "hidden",
        wordWrap: 'break-word',
        lineHeight: 1.2, // Améliore l'espacement des lignes
    },
    tableCellBold: {
        fontSize: 9,
        padding: 2,
        fontWeight: "bold",
        color: "#111827",
        overflow: "hidden",
        wordWrap: 'break-word',
        lineHeight: 1.2, // Améliore l'espacement des lignes
    },
    pageNumber: {
        position: "absolute",
        fontSize: 10,
        bottom: 30,
        left: 0,
        right: 0,
        textAlign: "center",
        color: "#9ca3af",
    },
    tocPage: {
        backgroundColor: "#f9fafb",
    },
    tocEntry: {
        fontSize: 12,
        marginBottom: 8,
        color: "#1f2937",
    },
    tocEntryLevel1: {
        fontSize: 14,
        fontWeight: "bold",
        marginBottom: 10,
        color: "#1e3a8a",
    },
    introText: {
        fontSize: 12,
        lineHeight: 1.6,
        color: "#4b5563",
        marginBottom: 10,
    },
    summaryBox: {
        backgroundColor: "#eff6ff",
        border: "1pt solid #3b82f6",
        borderRadius: 4,
        padding: 15,
        marginTop: 10,
        marginBottom: 15,
    },
    summaryText: {
        fontSize: 11,
        color: "#1e40af",
    },
}); 