// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package smart.proxies;

public class DateRange implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dateRangeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Smart.DateRange";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DateDebut("DateDebut"),
		DateFin("DateFin");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DateRange(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DateRange(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dateRangeMendixObject)
	{
		if (dateRangeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, dateRangeMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.dateRangeMendixObject = dateRangeMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static smart.proxies.DateRange initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new smart.proxies.DateRange(context, mendixObject);
	}

	public static smart.proxies.DateRange load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return smart.proxies.DateRange.initialize(context, mendixObject);
	}

	public static java.util.List<smart.proxies.DateRange> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> smart.proxies.DateRange.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of DateDebut
	 */
	public final java.util.Date getDateDebut()
	{
		return getDateDebut(getContext());
	}

	/**
	 * @param context
	 * @return value of DateDebut
	 */
	public final java.util.Date getDateDebut(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateDebut.toString());
	}

	/**
	 * Set value of DateDebut
	 * @param datedebut
	 */
	public final void setDateDebut(java.util.Date datedebut)
	{
		setDateDebut(getContext(), datedebut);
	}

	/**
	 * Set value of DateDebut
	 * @param context
	 * @param datedebut
	 */
	public final void setDateDebut(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datedebut)
	{
		getMendixObject().setValue(context, MemberNames.DateDebut.toString(), datedebut);
	}

	/**
	 * @return value of DateFin
	 */
	public final java.util.Date getDateFin()
	{
		return getDateFin(getContext());
	}

	/**
	 * @param context
	 * @return value of DateFin
	 */
	public final java.util.Date getDateFin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateFin.toString());
	}

	/**
	 * Set value of DateFin
	 * @param datefin
	 */
	public final void setDateFin(java.util.Date datefin)
	{
		setDateFin(getContext(), datefin);
	}

	/**
	 * Set value of DateFin
	 * @param context
	 * @param datefin
	 */
	public final void setDateFin(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datefin)
	{
		getMendixObject().setValue(context, MemberNames.DateFin.toString(), datefin);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dateRangeMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final smart.proxies.DateRange that = (smart.proxies.DateRange) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
