// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package smart.proxies;

public class DPESettingsForm implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dPESettingsFormMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Smart.DPESettingsForm";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ThresholdA_Day("ThresholdA_Day"),
		ThresholdB_Day("ThresholdB_Day"),
		ThresholdC_Day("ThresholdC_Day"),
		ThresholdD_Day("ThresholdD_Day"),
		ThresholdE_Day("ThresholdE_Day"),
		ThresholdF_Day("ThresholdF_Day"),
		ThresholdA_Week("ThresholdA_Week"),
		ThresholdB_Week("ThresholdB_Week"),
		ThresholdC_Week("ThresholdC_Week"),
		ThresholdD_Week("ThresholdD_Week"),
		ThresholdE_Week("ThresholdE_Week"),
		ThresholdF_Week("ThresholdF_Week"),
		ThresholdA_Month("ThresholdA_Month"),
		ThresholdB_Month("ThresholdB_Month"),
		ThresholdC_Month("ThresholdC_Month"),
		ThresholdD_Month("ThresholdD_Month"),
		ThresholdE_Month("ThresholdE_Month"),
		ThresholdF_Month("ThresholdF_Month");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DPESettingsForm(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DPESettingsForm(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dPESettingsFormMendixObject)
	{
		if (dPESettingsFormMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, dPESettingsFormMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.dPESettingsFormMendixObject = dPESettingsFormMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static smart.proxies.DPESettingsForm initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new smart.proxies.DPESettingsForm(context, mendixObject);
	}

	public static smart.proxies.DPESettingsForm load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return smart.proxies.DPESettingsForm.initialize(context, mendixObject);
	}

	/**
	 * @return value of ThresholdA_Day
	 */
	public final java.math.BigDecimal getThresholdA_Day()
	{
		return getThresholdA_Day(getContext());
	}

	/**
	 * @param context
	 * @return value of ThresholdA_Day
	 */
	public final java.math.BigDecimal getThresholdA_Day(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ThresholdA_Day.toString());
	}

	/**
	 * Set value of ThresholdA_Day
	 * @param thresholda_day
	 */
	public final void setThresholdA_Day(java.math.BigDecimal thresholda_day)
	{
		setThresholdA_Day(getContext(), thresholda_day);
	}

	/**
	 * Set value of ThresholdA_Day
	 * @param context
	 * @param thresholda_day
	 */
	public final void setThresholdA_Day(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal thresholda_day)
	{
		getMendixObject().setValue(context, MemberNames.ThresholdA_Day.toString(), thresholda_day);
	}

	/**
	 * @return value of ThresholdB_Day
	 */
	public final java.math.BigDecimal getThresholdB_Day()
	{
		return getThresholdB_Day(getContext());
	}

	/**
	 * @param context
	 * @return value of ThresholdB_Day
	 */
	public final java.math.BigDecimal getThresholdB_Day(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ThresholdB_Day.toString());
	}

	/**
	 * Set value of ThresholdB_Day
	 * @param thresholdb_day
	 */
	public final void setThresholdB_Day(java.math.BigDecimal thresholdb_day)
	{
		setThresholdB_Day(getContext(), thresholdb_day);
	}

	/**
	 * Set value of ThresholdB_Day
	 * @param context
	 * @param thresholdb_day
	 */
	public final void setThresholdB_Day(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal thresholdb_day)
	{
		getMendixObject().setValue(context, MemberNames.ThresholdB_Day.toString(), thresholdb_day);
	}

	/**
	 * @return value of ThresholdC_Day
	 */
	public final java.math.BigDecimal getThresholdC_Day()
	{
		return getThresholdC_Day(getContext());
	}

	/**
	 * @param context
	 * @return value of ThresholdC_Day
	 */
	public final java.math.BigDecimal getThresholdC_Day(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ThresholdC_Day.toString());
	}

	/**
	 * Set value of ThresholdC_Day
	 * @param thresholdc_day
	 */
	public final void setThresholdC_Day(java.math.BigDecimal thresholdc_day)
	{
		setThresholdC_Day(getContext(), thresholdc_day);
	}

	/**
	 * Set value of ThresholdC_Day
	 * @param context
	 * @param thresholdc_day
	 */
	public final void setThresholdC_Day(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal thresholdc_day)
	{
		getMendixObject().setValue(context, MemberNames.ThresholdC_Day.toString(), thresholdc_day);
	}

	/**
	 * @return value of ThresholdD_Day
	 */
	public final java.math.BigDecimal getThresholdD_Day()
	{
		return getThresholdD_Day(getContext());
	}

	/**
	 * @param context
	 * @return value of ThresholdD_Day
	 */
	public final java.math.BigDecimal getThresholdD_Day(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ThresholdD_Day.toString());
	}

	/**
	 * Set value of ThresholdD_Day
	 * @param thresholdd_day
	 */
	public final void setThresholdD_Day(java.math.BigDecimal thresholdd_day)
	{
		setThresholdD_Day(getContext(), thresholdd_day);
	}

	/**
	 * Set value of ThresholdD_Day
	 * @param context
	 * @param thresholdd_day
	 */
	public final void setThresholdD_Day(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal thresholdd_day)
	{
		getMendixObject().setValue(context, MemberNames.ThresholdD_Day.toString(), thresholdd_day);
	}

	/**
	 * @return value of ThresholdE_Day
	 */
	public final java.math.BigDecimal getThresholdE_Day()
	{
		return getThresholdE_Day(getContext());
	}

	/**
	 * @param context
	 * @return value of ThresholdE_Day
	 */
	public final java.math.BigDecimal getThresholdE_Day(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ThresholdE_Day.toString());
	}

	/**
	 * Set value of ThresholdE_Day
	 * @param thresholde_day
	 */
	public final void setThresholdE_Day(java.math.BigDecimal thresholde_day)
	{
		setThresholdE_Day(getContext(), thresholde_day);
	}

	/**
	 * Set value of ThresholdE_Day
	 * @param context
	 * @param thresholde_day
	 */
	public final void setThresholdE_Day(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal thresholde_day)
	{
		getMendixObject().setValue(context, MemberNames.ThresholdE_Day.toString(), thresholde_day);
	}

	/**
	 * @return value of ThresholdF_Day
	 */
	public final java.math.BigDecimal getThresholdF_Day()
	{
		return getThresholdF_Day(getContext());
	}

	/**
	 * @param context
	 * @return value of ThresholdF_Day
	 */
	public final java.math.BigDecimal getThresholdF_Day(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ThresholdF_Day.toString());
	}

	/**
	 * Set value of ThresholdF_Day
	 * @param thresholdf_day
	 */
	public final void setThresholdF_Day(java.math.BigDecimal thresholdf_day)
	{
		setThresholdF_Day(getContext(), thresholdf_day);
	}

	/**
	 * Set value of ThresholdF_Day
	 * @param context
	 * @param thresholdf_day
	 */
	public final void setThresholdF_Day(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal thresholdf_day)
	{
		getMendixObject().setValue(context, MemberNames.ThresholdF_Day.toString(), thresholdf_day);
	}

	/**
	 * @return value of ThresholdA_Week
	 */
	public final java.math.BigDecimal getThresholdA_Week()
	{
		return getThresholdA_Week(getContext());
	}

	/**
	 * @param context
	 * @return value of ThresholdA_Week
	 */
	public final java.math.BigDecimal getThresholdA_Week(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ThresholdA_Week.toString());
	}

	/**
	 * Set value of ThresholdA_Week
	 * @param thresholda_week
	 */
	public final void setThresholdA_Week(java.math.BigDecimal thresholda_week)
	{
		setThresholdA_Week(getContext(), thresholda_week);
	}

	/**
	 * Set value of ThresholdA_Week
	 * @param context
	 * @param thresholda_week
	 */
	public final void setThresholdA_Week(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal thresholda_week)
	{
		getMendixObject().setValue(context, MemberNames.ThresholdA_Week.toString(), thresholda_week);
	}

	/**
	 * @return value of ThresholdB_Week
	 */
	public final java.math.BigDecimal getThresholdB_Week()
	{
		return getThresholdB_Week(getContext());
	}

	/**
	 * @param context
	 * @return value of ThresholdB_Week
	 */
	public final java.math.BigDecimal getThresholdB_Week(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ThresholdB_Week.toString());
	}

	/**
	 * Set value of ThresholdB_Week
	 * @param thresholdb_week
	 */
	public final void setThresholdB_Week(java.math.BigDecimal thresholdb_week)
	{
		setThresholdB_Week(getContext(), thresholdb_week);
	}

	/**
	 * Set value of ThresholdB_Week
	 * @param context
	 * @param thresholdb_week
	 */
	public final void setThresholdB_Week(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal thresholdb_week)
	{
		getMendixObject().setValue(context, MemberNames.ThresholdB_Week.toString(), thresholdb_week);
	}

	/**
	 * @return value of ThresholdC_Week
	 */
	public final java.math.BigDecimal getThresholdC_Week()
	{
		return getThresholdC_Week(getContext());
	}

	/**
	 * @param context
	 * @return value of ThresholdC_Week
	 */
	public final java.math.BigDecimal getThresholdC_Week(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ThresholdC_Week.toString());
	}

	/**
	 * Set value of ThresholdC_Week
	 * @param thresholdc_week
	 */
	public final void setThresholdC_Week(java.math.BigDecimal thresholdc_week)
	{
		setThresholdC_Week(getContext(), thresholdc_week);
	}

	/**
	 * Set value of ThresholdC_Week
	 * @param context
	 * @param thresholdc_week
	 */
	public final void setThresholdC_Week(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal thresholdc_week)
	{
		getMendixObject().setValue(context, MemberNames.ThresholdC_Week.toString(), thresholdc_week);
	}

	/**
	 * @return value of ThresholdD_Week
	 */
	public final java.math.BigDecimal getThresholdD_Week()
	{
		return getThresholdD_Week(getContext());
	}

	/**
	 * @param context
	 * @return value of ThresholdD_Week
	 */
	public final java.math.BigDecimal getThresholdD_Week(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ThresholdD_Week.toString());
	}

	/**
	 * Set value of ThresholdD_Week
	 * @param thresholdd_week
	 */
	public final void setThresholdD_Week(java.math.BigDecimal thresholdd_week)
	{
		setThresholdD_Week(getContext(), thresholdd_week);
	}

	/**
	 * Set value of ThresholdD_Week
	 * @param context
	 * @param thresholdd_week
	 */
	public final void setThresholdD_Week(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal thresholdd_week)
	{
		getMendixObject().setValue(context, MemberNames.ThresholdD_Week.toString(), thresholdd_week);
	}

	/**
	 * @return value of ThresholdE_Week
	 */
	public final java.math.BigDecimal getThresholdE_Week()
	{
		return getThresholdE_Week(getContext());
	}

	/**
	 * @param context
	 * @return value of ThresholdE_Week
	 */
	public final java.math.BigDecimal getThresholdE_Week(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ThresholdE_Week.toString());
	}

	/**
	 * Set value of ThresholdE_Week
	 * @param thresholde_week
	 */
	public final void setThresholdE_Week(java.math.BigDecimal thresholde_week)
	{
		setThresholdE_Week(getContext(), thresholde_week);
	}

	/**
	 * Set value of ThresholdE_Week
	 * @param context
	 * @param thresholde_week
	 */
	public final void setThresholdE_Week(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal thresholde_week)
	{
		getMendixObject().setValue(context, MemberNames.ThresholdE_Week.toString(), thresholde_week);
	}

	/**
	 * @return value of ThresholdF_Week
	 */
	public final java.math.BigDecimal getThresholdF_Week()
	{
		return getThresholdF_Week(getContext());
	}

	/**
	 * @param context
	 * @return value of ThresholdF_Week
	 */
	public final java.math.BigDecimal getThresholdF_Week(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ThresholdF_Week.toString());
	}

	/**
	 * Set value of ThresholdF_Week
	 * @param thresholdf_week
	 */
	public final void setThresholdF_Week(java.math.BigDecimal thresholdf_week)
	{
		setThresholdF_Week(getContext(), thresholdf_week);
	}

	/**
	 * Set value of ThresholdF_Week
	 * @param context
	 * @param thresholdf_week
	 */
	public final void setThresholdF_Week(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal thresholdf_week)
	{
		getMendixObject().setValue(context, MemberNames.ThresholdF_Week.toString(), thresholdf_week);
	}

	/**
	 * @return value of ThresholdA_Month
	 */
	public final java.math.BigDecimal getThresholdA_Month()
	{
		return getThresholdA_Month(getContext());
	}

	/**
	 * @param context
	 * @return value of ThresholdA_Month
	 */
	public final java.math.BigDecimal getThresholdA_Month(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ThresholdA_Month.toString());
	}

	/**
	 * Set value of ThresholdA_Month
	 * @param thresholda_month
	 */
	public final void setThresholdA_Month(java.math.BigDecimal thresholda_month)
	{
		setThresholdA_Month(getContext(), thresholda_month);
	}

	/**
	 * Set value of ThresholdA_Month
	 * @param context
	 * @param thresholda_month
	 */
	public final void setThresholdA_Month(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal thresholda_month)
	{
		getMendixObject().setValue(context, MemberNames.ThresholdA_Month.toString(), thresholda_month);
	}

	/**
	 * @return value of ThresholdB_Month
	 */
	public final java.math.BigDecimal getThresholdB_Month()
	{
		return getThresholdB_Month(getContext());
	}

	/**
	 * @param context
	 * @return value of ThresholdB_Month
	 */
	public final java.math.BigDecimal getThresholdB_Month(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ThresholdB_Month.toString());
	}

	/**
	 * Set value of ThresholdB_Month
	 * @param thresholdb_month
	 */
	public final void setThresholdB_Month(java.math.BigDecimal thresholdb_month)
	{
		setThresholdB_Month(getContext(), thresholdb_month);
	}

	/**
	 * Set value of ThresholdB_Month
	 * @param context
	 * @param thresholdb_month
	 */
	public final void setThresholdB_Month(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal thresholdb_month)
	{
		getMendixObject().setValue(context, MemberNames.ThresholdB_Month.toString(), thresholdb_month);
	}

	/**
	 * @return value of ThresholdC_Month
	 */
	public final java.math.BigDecimal getThresholdC_Month()
	{
		return getThresholdC_Month(getContext());
	}

	/**
	 * @param context
	 * @return value of ThresholdC_Month
	 */
	public final java.math.BigDecimal getThresholdC_Month(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ThresholdC_Month.toString());
	}

	/**
	 * Set value of ThresholdC_Month
	 * @param thresholdc_month
	 */
	public final void setThresholdC_Month(java.math.BigDecimal thresholdc_month)
	{
		setThresholdC_Month(getContext(), thresholdc_month);
	}

	/**
	 * Set value of ThresholdC_Month
	 * @param context
	 * @param thresholdc_month
	 */
	public final void setThresholdC_Month(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal thresholdc_month)
	{
		getMendixObject().setValue(context, MemberNames.ThresholdC_Month.toString(), thresholdc_month);
	}

	/**
	 * @return value of ThresholdD_Month
	 */
	public final java.math.BigDecimal getThresholdD_Month()
	{
		return getThresholdD_Month(getContext());
	}

	/**
	 * @param context
	 * @return value of ThresholdD_Month
	 */
	public final java.math.BigDecimal getThresholdD_Month(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ThresholdD_Month.toString());
	}

	/**
	 * Set value of ThresholdD_Month
	 * @param thresholdd_month
	 */
	public final void setThresholdD_Month(java.math.BigDecimal thresholdd_month)
	{
		setThresholdD_Month(getContext(), thresholdd_month);
	}

	/**
	 * Set value of ThresholdD_Month
	 * @param context
	 * @param thresholdd_month
	 */
	public final void setThresholdD_Month(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal thresholdd_month)
	{
		getMendixObject().setValue(context, MemberNames.ThresholdD_Month.toString(), thresholdd_month);
	}

	/**
	 * @return value of ThresholdE_Month
	 */
	public final java.math.BigDecimal getThresholdE_Month()
	{
		return getThresholdE_Month(getContext());
	}

	/**
	 * @param context
	 * @return value of ThresholdE_Month
	 */
	public final java.math.BigDecimal getThresholdE_Month(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ThresholdE_Month.toString());
	}

	/**
	 * Set value of ThresholdE_Month
	 * @param thresholde_month
	 */
	public final void setThresholdE_Month(java.math.BigDecimal thresholde_month)
	{
		setThresholdE_Month(getContext(), thresholde_month);
	}

	/**
	 * Set value of ThresholdE_Month
	 * @param context
	 * @param thresholde_month
	 */
	public final void setThresholdE_Month(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal thresholde_month)
	{
		getMendixObject().setValue(context, MemberNames.ThresholdE_Month.toString(), thresholde_month);
	}

	/**
	 * @return value of ThresholdF_Month
	 */
	public final java.math.BigDecimal getThresholdF_Month()
	{
		return getThresholdF_Month(getContext());
	}

	/**
	 * @param context
	 * @return value of ThresholdF_Month
	 */
	public final java.math.BigDecimal getThresholdF_Month(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ThresholdF_Month.toString());
	}

	/**
	 * Set value of ThresholdF_Month
	 * @param thresholdf_month
	 */
	public final void setThresholdF_Month(java.math.BigDecimal thresholdf_month)
	{
		setThresholdF_Month(getContext(), thresholdf_month);
	}

	/**
	 * Set value of ThresholdF_Month
	 * @param context
	 * @param thresholdf_month
	 */
	public final void setThresholdF_Month(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal thresholdf_month)
	{
		getMendixObject().setValue(context, MemberNames.ThresholdF_Month.toString(), thresholdf_month);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dPESettingsFormMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final smart.proxies.DPESettingsForm that = (smart.proxies.DPESettingsForm) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
