// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package smart.proxies;

public enum Features
{
	Rapport(new java.lang.String[][] { new java.lang.String[] { "en_US", "Rapport MWF" } }),
	Double_IPE(new java.lang.String[][] { new java.lang.String[] { "en_US", "Double IPE" } }),
	Tableau(new java.lang.String[][] { new java.lang.String[] { "en_US", "Tableau" } }),
	Granularite_Manuelle(new java.lang.String[][] { new java.lang.String[] { "en_US", "Granularite_Manuelle" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Features(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
