// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package smart.proxies;

public class Level implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject levelMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Smart.Level";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		SortOrder("SortOrder"),
		AssetCount("AssetCount"),
		ConsoTotalElec("ConsoTotalElec"),
		ConsoTotalGaz("ConsoTotalGaz"),
		ConsoTotalEau("ConsoTotalEau"),
		ConsoTotalAir("ConsoTotalAir"),
		IPETotalElec("IPETotalElec"),
		IPETotalGaz("IPETotalGaz"),
		IPETotalEau("IPETotalEau"),
		IPETotalAir("IPETotalAir");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Level(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Level(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject levelMendixObject)
	{
		if (levelMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, levelMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.levelMendixObject = levelMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static smart.proxies.Level initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new smart.proxies.Level(context, mendixObject);
	}

	public static smart.proxies.Level load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return smart.proxies.Level.initialize(context, mendixObject);
	}

	public static java.util.List<smart.proxies.Level> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> smart.proxies.Level.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of SortOrder
	 */
	public final java.lang.Integer getSortOrder()
	{
		return getSortOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of SortOrder
	 */
	public final java.lang.Integer getSortOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SortOrder.toString());
	}

	/**
	 * Set value of SortOrder
	 * @param sortorder
	 */
	public final void setSortOrder(java.lang.Integer sortorder)
	{
		setSortOrder(getContext(), sortorder);
	}

	/**
	 * Set value of SortOrder
	 * @param context
	 * @param sortorder
	 */
	public final void setSortOrder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sortorder)
	{
		getMendixObject().setValue(context, MemberNames.SortOrder.toString(), sortorder);
	}

	/**
	 * @return value of AssetCount
	 */
	public final java.lang.Integer getAssetCount()
	{
		return getAssetCount(getContext());
	}

	/**
	 * @param context
	 * @return value of AssetCount
	 */
	public final java.lang.Integer getAssetCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.AssetCount.toString());
	}

	/**
	 * Set value of AssetCount
	 * @param assetcount
	 */
	public final void setAssetCount(java.lang.Integer assetcount)
	{
		setAssetCount(getContext(), assetcount);
	}

	/**
	 * Set value of AssetCount
	 * @param context
	 * @param assetcount
	 */
	public final void setAssetCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer assetcount)
	{
		getMendixObject().setValue(context, MemberNames.AssetCount.toString(), assetcount);
	}

	/**
	 * @return value of ConsoTotalElec
	 */
	public final java.math.BigDecimal getConsoTotalElec()
	{
		return getConsoTotalElec(getContext());
	}

	/**
	 * @param context
	 * @return value of ConsoTotalElec
	 */
	public final java.math.BigDecimal getConsoTotalElec(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ConsoTotalElec.toString());
	}

	/**
	 * Set value of ConsoTotalElec
	 * @param consototalelec
	 */
	public final void setConsoTotalElec(java.math.BigDecimal consototalelec)
	{
		setConsoTotalElec(getContext(), consototalelec);
	}

	/**
	 * Set value of ConsoTotalElec
	 * @param context
	 * @param consototalelec
	 */
	public final void setConsoTotalElec(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal consototalelec)
	{
		getMendixObject().setValue(context, MemberNames.ConsoTotalElec.toString(), consototalelec);
	}

	/**
	 * @return value of ConsoTotalGaz
	 */
	public final java.math.BigDecimal getConsoTotalGaz()
	{
		return getConsoTotalGaz(getContext());
	}

	/**
	 * @param context
	 * @return value of ConsoTotalGaz
	 */
	public final java.math.BigDecimal getConsoTotalGaz(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ConsoTotalGaz.toString());
	}

	/**
	 * Set value of ConsoTotalGaz
	 * @param consototalgaz
	 */
	public final void setConsoTotalGaz(java.math.BigDecimal consototalgaz)
	{
		setConsoTotalGaz(getContext(), consototalgaz);
	}

	/**
	 * Set value of ConsoTotalGaz
	 * @param context
	 * @param consototalgaz
	 */
	public final void setConsoTotalGaz(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal consototalgaz)
	{
		getMendixObject().setValue(context, MemberNames.ConsoTotalGaz.toString(), consototalgaz);
	}

	/**
	 * @return value of ConsoTotalEau
	 */
	public final java.math.BigDecimal getConsoTotalEau()
	{
		return getConsoTotalEau(getContext());
	}

	/**
	 * @param context
	 * @return value of ConsoTotalEau
	 */
	public final java.math.BigDecimal getConsoTotalEau(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ConsoTotalEau.toString());
	}

	/**
	 * Set value of ConsoTotalEau
	 * @param consototaleau
	 */
	public final void setConsoTotalEau(java.math.BigDecimal consototaleau)
	{
		setConsoTotalEau(getContext(), consototaleau);
	}

	/**
	 * Set value of ConsoTotalEau
	 * @param context
	 * @param consototaleau
	 */
	public final void setConsoTotalEau(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal consototaleau)
	{
		getMendixObject().setValue(context, MemberNames.ConsoTotalEau.toString(), consototaleau);
	}

	/**
	 * @return value of ConsoTotalAir
	 */
	public final java.math.BigDecimal getConsoTotalAir()
	{
		return getConsoTotalAir(getContext());
	}

	/**
	 * @param context
	 * @return value of ConsoTotalAir
	 */
	public final java.math.BigDecimal getConsoTotalAir(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ConsoTotalAir.toString());
	}

	/**
	 * Set value of ConsoTotalAir
	 * @param consototalair
	 */
	public final void setConsoTotalAir(java.math.BigDecimal consototalair)
	{
		setConsoTotalAir(getContext(), consototalair);
	}

	/**
	 * Set value of ConsoTotalAir
	 * @param context
	 * @param consototalair
	 */
	public final void setConsoTotalAir(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal consototalair)
	{
		getMendixObject().setValue(context, MemberNames.ConsoTotalAir.toString(), consototalair);
	}

	/**
	 * @return value of IPETotalElec
	 */
	public final java.math.BigDecimal getIPETotalElec()
	{
		return getIPETotalElec(getContext());
	}

	/**
	 * @param context
	 * @return value of IPETotalElec
	 */
	public final java.math.BigDecimal getIPETotalElec(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.IPETotalElec.toString());
	}

	/**
	 * Set value of IPETotalElec
	 * @param ipetotalelec
	 */
	public final void setIPETotalElec(java.math.BigDecimal ipetotalelec)
	{
		setIPETotalElec(getContext(), ipetotalelec);
	}

	/**
	 * Set value of IPETotalElec
	 * @param context
	 * @param ipetotalelec
	 */
	public final void setIPETotalElec(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal ipetotalelec)
	{
		getMendixObject().setValue(context, MemberNames.IPETotalElec.toString(), ipetotalelec);
	}

	/**
	 * @return value of IPETotalGaz
	 */
	public final java.math.BigDecimal getIPETotalGaz()
	{
		return getIPETotalGaz(getContext());
	}

	/**
	 * @param context
	 * @return value of IPETotalGaz
	 */
	public final java.math.BigDecimal getIPETotalGaz(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.IPETotalGaz.toString());
	}

	/**
	 * Set value of IPETotalGaz
	 * @param ipetotalgaz
	 */
	public final void setIPETotalGaz(java.math.BigDecimal ipetotalgaz)
	{
		setIPETotalGaz(getContext(), ipetotalgaz);
	}

	/**
	 * Set value of IPETotalGaz
	 * @param context
	 * @param ipetotalgaz
	 */
	public final void setIPETotalGaz(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal ipetotalgaz)
	{
		getMendixObject().setValue(context, MemberNames.IPETotalGaz.toString(), ipetotalgaz);
	}

	/**
	 * @return value of IPETotalEau
	 */
	public final java.math.BigDecimal getIPETotalEau()
	{
		return getIPETotalEau(getContext());
	}

	/**
	 * @param context
	 * @return value of IPETotalEau
	 */
	public final java.math.BigDecimal getIPETotalEau(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.IPETotalEau.toString());
	}

	/**
	 * Set value of IPETotalEau
	 * @param ipetotaleau
	 */
	public final void setIPETotalEau(java.math.BigDecimal ipetotaleau)
	{
		setIPETotalEau(getContext(), ipetotaleau);
	}

	/**
	 * Set value of IPETotalEau
	 * @param context
	 * @param ipetotaleau
	 */
	public final void setIPETotalEau(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal ipetotaleau)
	{
		getMendixObject().setValue(context, MemberNames.IPETotalEau.toString(), ipetotaleau);
	}

	/**
	 * @return value of IPETotalAir
	 */
	public final java.math.BigDecimal getIPETotalAir()
	{
		return getIPETotalAir(getContext());
	}

	/**
	 * @param context
	 * @return value of IPETotalAir
	 */
	public final java.math.BigDecimal getIPETotalAir(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.IPETotalAir.toString());
	}

	/**
	 * Set value of IPETotalAir
	 * @param ipetotalair
	 */
	public final void setIPETotalAir(java.math.BigDecimal ipetotalair)
	{
		setIPETotalAir(getContext(), ipetotalair);
	}

	/**
	 * Set value of IPETotalAir
	 * @param context
	 * @param ipetotalair
	 */
	public final void setIPETotalAir(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal ipetotalair)
	{
		getMendixObject().setValue(context, MemberNames.IPETotalAir.toString(), ipetotalair);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return levelMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final smart.proxies.Level that = (smart.proxies.Level) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
