// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package smart.proxies;

public class TimeSeriesPoint implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject timeSeriesPointMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Smart.TimeSeriesPoint";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Timestamp("Timestamp"),
		Value("Value"),
		TimeSeriesPoint_Asset("Smart.TimeSeriesPoint_Asset"),
		TimeSeriesPoint_Variable("Smart.TimeSeriesPoint_Variable");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TimeSeriesPoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TimeSeriesPoint(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject timeSeriesPointMendixObject)
	{
		if (timeSeriesPointMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, timeSeriesPointMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.timeSeriesPointMendixObject = timeSeriesPointMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static smart.proxies.TimeSeriesPoint initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new smart.proxies.TimeSeriesPoint(context, mendixObject);
	}

	public static smart.proxies.TimeSeriesPoint load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return smart.proxies.TimeSeriesPoint.initialize(context, mendixObject);
	}

	public static java.util.List<smart.proxies.TimeSeriesPoint> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> smart.proxies.TimeSeriesPoint.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Timestamp
	 */
	public final java.util.Date getTimestamp()
	{
		return getTimestamp(getContext());
	}

	/**
	 * @param context
	 * @return value of Timestamp
	 */
	public final java.util.Date getTimestamp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Timestamp.toString());
	}

	/**
	 * Set value of Timestamp
	 * @param timestamp
	 */
	public final void setTimestamp(java.util.Date timestamp)
	{
		setTimestamp(getContext(), timestamp);
	}

	/**
	 * Set value of Timestamp
	 * @param context
	 * @param timestamp
	 */
	public final void setTimestamp(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date timestamp)
	{
		getMendixObject().setValue(context, MemberNames.Timestamp.toString(), timestamp);
	}

	/**
	 * @return value of Value
	 */
	public final java.math.BigDecimal getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.math.BigDecimal getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.math.BigDecimal value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TimeSeriesPoint_Asset
	 */
	public final smart.proxies.Asset getTimeSeriesPoint_Asset() throws com.mendix.core.CoreException
	{
		return getTimeSeriesPoint_Asset(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeSeriesPoint_Asset
	 * @throws com.mendix.core.CoreException
	 */
	public final smart.proxies.Asset getTimeSeriesPoint_Asset(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		smart.proxies.Asset result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TimeSeriesPoint_Asset.toString());
		if (identifier != null) {
			result = smart.proxies.Asset.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TimeSeriesPoint_Asset
	 * @param timeseriespoint_asset
	 */
	public final void setTimeSeriesPoint_Asset(smart.proxies.Asset timeseriespoint_asset)
	{
		setTimeSeriesPoint_Asset(getContext(), timeseriespoint_asset);
	}

	/**
	 * Set value of TimeSeriesPoint_Asset
	 * @param context
	 * @param timeseriespoint_asset
	 */
	public final void setTimeSeriesPoint_Asset(com.mendix.systemwideinterfaces.core.IContext context, smart.proxies.Asset timeseriespoint_asset)
	{
		if (timeseriespoint_asset == null) {
			getMendixObject().setValue(context, MemberNames.TimeSeriesPoint_Asset.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TimeSeriesPoint_Asset.toString(), timeseriespoint_asset.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TimeSeriesPoint_Variable
	 */
	public final smart.proxies.Variable getTimeSeriesPoint_Variable() throws com.mendix.core.CoreException
	{
		return getTimeSeriesPoint_Variable(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeSeriesPoint_Variable
	 * @throws com.mendix.core.CoreException
	 */
	public final smart.proxies.Variable getTimeSeriesPoint_Variable(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		smart.proxies.Variable result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TimeSeriesPoint_Variable.toString());
		if (identifier != null) {
			result = smart.proxies.Variable.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TimeSeriesPoint_Variable
	 * @param timeseriespoint_variable
	 */
	public final void setTimeSeriesPoint_Variable(smart.proxies.Variable timeseriespoint_variable)
	{
		setTimeSeriesPoint_Variable(getContext(), timeseriespoint_variable);
	}

	/**
	 * Set value of TimeSeriesPoint_Variable
	 * @param context
	 * @param timeseriespoint_variable
	 */
	public final void setTimeSeriesPoint_Variable(com.mendix.systemwideinterfaces.core.IContext context, smart.proxies.Variable timeseriespoint_variable)
	{
		if (timeseriespoint_variable == null) {
			getMendixObject().setValue(context, MemberNames.TimeSeriesPoint_Variable.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TimeSeriesPoint_Variable.toString(), timeseriespoint_variable.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return timeSeriesPointMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final smart.proxies.TimeSeriesPoint that = (smart.proxies.TimeSeriesPoint) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
