// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package smart.proxies;

public class EnergyFlowNode implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject energyFlowNodeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Smart.EnergyFlowNode";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FlowValue("FlowValue"),
		Percentage("Percentage"),
		SourceAsset("Smart.SourceAsset"),
		TargetAsset("Smart.TargetAsset");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EnergyFlowNode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EnergyFlowNode(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject energyFlowNodeMendixObject)
	{
		if (energyFlowNodeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, energyFlowNodeMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.energyFlowNodeMendixObject = energyFlowNodeMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static smart.proxies.EnergyFlowNode initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new smart.proxies.EnergyFlowNode(context, mendixObject);
	}

	public static smart.proxies.EnergyFlowNode load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return smart.proxies.EnergyFlowNode.initialize(context, mendixObject);
	}

	public static java.util.List<smart.proxies.EnergyFlowNode> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> smart.proxies.EnergyFlowNode.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of FlowValue
	 */
	public final java.math.BigDecimal getFlowValue()
	{
		return getFlowValue(getContext());
	}

	/**
	 * @param context
	 * @return value of FlowValue
	 */
	public final java.math.BigDecimal getFlowValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.FlowValue.toString());
	}

	/**
	 * Set value of FlowValue
	 * @param flowvalue
	 */
	public final void setFlowValue(java.math.BigDecimal flowvalue)
	{
		setFlowValue(getContext(), flowvalue);
	}

	/**
	 * Set value of FlowValue
	 * @param context
	 * @param flowvalue
	 */
	public final void setFlowValue(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal flowvalue)
	{
		getMendixObject().setValue(context, MemberNames.FlowValue.toString(), flowvalue);
	}

	/**
	 * @return value of Percentage
	 */
	public final java.math.BigDecimal getPercentage()
	{
		return getPercentage(getContext());
	}

	/**
	 * @param context
	 * @return value of Percentage
	 */
	public final java.math.BigDecimal getPercentage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Percentage.toString());
	}

	/**
	 * Set value of Percentage
	 * @param percentage
	 */
	public final void setPercentage(java.math.BigDecimal percentage)
	{
		setPercentage(getContext(), percentage);
	}

	/**
	 * Set value of Percentage
	 * @param context
	 * @param percentage
	 */
	public final void setPercentage(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal percentage)
	{
		getMendixObject().setValue(context, MemberNames.Percentage.toString(), percentage);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SourceAsset
	 */
	public final smart.proxies.Asset getSourceAsset() throws com.mendix.core.CoreException
	{
		return getSourceAsset(getContext());
	}

	/**
	 * @param context
	 * @return value of SourceAsset
	 * @throws com.mendix.core.CoreException
	 */
	public final smart.proxies.Asset getSourceAsset(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		smart.proxies.Asset result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SourceAsset.toString());
		if (identifier != null) {
			result = smart.proxies.Asset.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SourceAsset
	 * @param sourceasset
	 */
	public final void setSourceAsset(smart.proxies.Asset sourceasset)
	{
		setSourceAsset(getContext(), sourceasset);
	}

	/**
	 * Set value of SourceAsset
	 * @param context
	 * @param sourceasset
	 */
	public final void setSourceAsset(com.mendix.systemwideinterfaces.core.IContext context, smart.proxies.Asset sourceasset)
	{
		if (sourceasset == null) {
			getMendixObject().setValue(context, MemberNames.SourceAsset.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SourceAsset.toString(), sourceasset.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TargetAsset
	 */
	public final smart.proxies.Asset getTargetAsset() throws com.mendix.core.CoreException
	{
		return getTargetAsset(getContext());
	}

	/**
	 * @param context
	 * @return value of TargetAsset
	 * @throws com.mendix.core.CoreException
	 */
	public final smart.proxies.Asset getTargetAsset(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		smart.proxies.Asset result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TargetAsset.toString());
		if (identifier != null) {
			result = smart.proxies.Asset.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TargetAsset
	 * @param targetasset
	 */
	public final void setTargetAsset(smart.proxies.Asset targetasset)
	{
		setTargetAsset(getContext(), targetasset);
	}

	/**
	 * Set value of TargetAsset
	 * @param context
	 * @param targetasset
	 */
	public final void setTargetAsset(com.mendix.systemwideinterfaces.core.IContext context, smart.proxies.Asset targetasset)
	{
		if (targetasset == null) {
			getMendixObject().setValue(context, MemberNames.TargetAsset.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TargetAsset.toString(), targetasset.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return energyFlowNodeMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final smart.proxies.EnergyFlowNode that = (smart.proxies.EnergyFlowNode) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
