// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package smart.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import com.mendix.logging.ILogNode;
import smart.proxies.FeatureToggle;
import smart.proxies.Features;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

public class InitializeFeatureToggles extends CustomJavaAction<java.lang.Void>
{
	public InitializeFeatureToggles(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
        IContext ctx = getContext();
        
        getLogger().info("=== INITIALISATION FEATURE TOGGLES ===");
        getLogger().info("🎯 Système global");

        InitializationStats stats = new InitializationStats();
        long startTime = System.currentTimeMillis();

        try {
            // 🚀 INITIALISATION AUTOMATIQUE : Traiter toutes les features de l'énumération
            getLogger().info("🔄 Initialisation automatique de toutes les features...");
            
            for (Features feature : Features.values()) {
                // Définir un comportement par défaut pour chaque feature
                boolean defaultEnabled = getDefaultEnabledState(feature);
                String description = "Auto-init " + feature.toString();

                // Appeler la fonction d'initialisation
                initializeFeature(ctx, feature, defaultEnabled, description, stats);
            }

            // 🧹 NETTOYAGE : Supprimer les lignes obsolètes
            cleanupObsoleteToggles(ctx, stats);

            // Logs finaux
            long duration = System.currentTimeMillis() - startTime;
            logFinalStats(stats, duration);

            return null; // Void return type

        } catch (Exception e) {
            long duration = System.currentTimeMillis() - startTime;
            getLogger().error("💥 Erreur critique initialisation Feature Toggles: " + e.getMessage(), e);
            logFinalStats(stats, duration);
            throw e;
        }
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "InitializeFeatureToggles";
	}

	// BEGIN EXTRA CODE
    /* ==== LOGGER ==== */
    private static final ILogNode LOG = Core.getLogger("FeatureToggleInit");
    
    private ILogNode getLogger() {
        return LOG;
    }

    /* ==== STATISTIQUES D'INITIALISATION ==== */
    private static class InitializationStats {
        int featuresProcessed = 0;
        int togglesCreated = 0;
        int togglesUpdated = 0;
        int togglesSkipped = 0;
        int togglesDeleted = 0; // 🆕 Nouveau compteur pour les suppressions
        int errors = 0;
    }

    /* ==== NETTOYAGE DES LIGNES OBSOLÈTES ==== */
    private void cleanupObsoleteToggles(IContext ctx, InitializationStats stats) throws Exception {
        getLogger().info("🧹 Début du nettoyage des Feature Toggles obsolètes...");
        
        try {
            // Récupérer tous les literals actuels de l'énumération Features
            Set<String> enumLiterals = getCurrentEnumLiterals();
            getLogger().debug("📋 Literals actuels de l'énumération: " + enumLiterals);
            
            // Récupérer tous les FeatureToggles existants dans la BDD
            List<IMendixObject> allToggles = Core.retrieveXPathQuery(ctx, "//Smart.FeatureToggle");
            getLogger().debug("🔍 " + allToggles.size() + " Feature Toggles trouvés en BDD");
            
            int deletedCount = 0;
            
            for (IMendixObject toggle : allToggles) {
                String featureName = (String) toggle.getValue(ctx, "FeatureName");
                
                if (featureName != null && !enumLiterals.contains(featureName)) {
                    // Ce FeatureToggle correspond à un literal qui n'existe plus
                    getLogger().info("🗑️ Suppression Feature Toggle obsolète: " + featureName);
                    Core.delete(ctx, toggle);
                    deletedCount++;
                }
            }
            
            stats.togglesDeleted = deletedCount;
            getLogger().info("✅ Nettoyage terminé: " + deletedCount + " Feature Toggles obsolètes supprimés");
            
        } catch (Exception e) {
            stats.errors++;
            getLogger().error("❌ Erreur lors du nettoyage des Feature Toggles obsolètes: " + e.getMessage(), e);
            throw e;
        }
    }
    
    /* ==== RÉCUPÉRATION DES LITERALS ACTUELS ==== */
    private Set<String> getCurrentEnumLiterals() {
        Set<String> literals = new java.util.HashSet<>();
        
        // ✅ AUTOMATISATION : Récupération dynamique de tous les literals
        for (Features feature : Features.values()) {
            literals.add(feature.toString());
        }
        
        getLogger().debug("📋 Literals récupérés dynamiquement: " + literals);
        return literals;
    }

    /* ==== DÉFINITION DES VALEURS PAR DÉFAUT ==== */
    private boolean getDefaultEnabledState(Features feature) {
        // Définir les valeurs par défaut pour chaque feature
        switch (feature) {
            case Double_IPE:
                return false; // Calcul IPE alternatif désactivé par défaut
            case Rapport:
                return true;  // Rapports activés par défaut
            default:
                // Pour toute nouvelle feature, désactivée par défaut (principe de sécurité)
                getLogger().info("⚠️ Nouvelle feature détectée: " + feature.toString() + " - désactivée par défaut");
                return false;
        }
    }

    /* ==== INITIALISATION D'UNE FEATURE SPÉCIFIQUE ==== */
    private void initializeFeature(IContext ctx, Features feature, 
                                 boolean defaultEnabled, String description, InitializationStats stats) throws Exception {
        
        stats.featuresProcessed++;
        
        getLogger().debug("🔍 Traitement feature: " + feature.toString());

        // Vérifier si le toggle existe déjà pour cette feature (par valeur d'énum, pas caption)
        String xpath = String.format(
            "//Smart.FeatureToggle[FeatureName='%s']",
            feature.toString() // Utilise la valeur d'énum (ex: "Double_IPE"), pas le caption
        );
        
        List<IMendixObject> existing = Core.retrieveXPathQuery(ctx, xpath);

        if (existing.isEmpty()) {
            // Créer un nouveau FeatureToggle (create-missing-only)
            FeatureToggle newToggle = new FeatureToggle(ctx);
            
            // Définir les propriétés avec type safety complet
            newToggle.setFeatureName(feature);  // Type-safe assignment
            newToggle.setIsEnabled(defaultEnabled);
            newToggle.setConfigurationValue(""); // Configuration vide pour système global
            
            Core.commit(ctx, newToggle.getMendixObject());
            stats.togglesCreated++;
            
            getLogger().info("✨ Feature Toggle créé: " + feature.toString() + " (enabled: " + defaultEnabled + ")");
            
        } else {
            // NE PAS TOUCHER IsEnabled ni ConfigurationValue si la ligne existe déjà
            // L'administrateur a peut-être modifié ces valeurs
            stats.togglesSkipped++;
            
            getLogger().debug("⏭️ Feature Toggle existant ignoré: " + feature.toString() + " (valeurs préservées)");
        }
    }

    /* ==== LOGS FINAUX ==== */
    private void logFinalStats(InitializationStats stats, long durationMs) {
        getLogger().info("=== STATISTIQUES INITIALISATION FINALES ===");
        getLogger().info("⏱️ Durée totale: " + durationMs + "ms (" + String.format("%.2f", durationMs/1000.0) + "s)");
        getLogger().info("📊 Features traitées: " + stats.featuresProcessed);
        getLogger().info("✨ Feature Toggles créés: " + stats.togglesCreated);
        getLogger().info("🔄 Feature Toggles mis à jour: " + stats.togglesUpdated);
        getLogger().info("⏭️ Feature Toggles ignorés: " + stats.togglesSkipped);
        getLogger().info("🗑️ Feature Toggles supprimés: " + stats.togglesDeleted); // 🆕 Nouveau log
        getLogger().info("❌ Erreurs rencontrées: " + stats.errors);
        
        if (stats.featuresProcessed > 0) {
            double avgTimePerFeature = (double) durationMs / stats.featuresProcessed;
            getLogger().info("📈 Temps moyen par feature: " + String.format("%.2f", avgTimePerFeature) + "ms");
        }
        
        getLogger().info("=== FIN INITIALISATION FEATURE TOGGLES ===");
    }
	// END EXTRA CODE
}
