// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package smart.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import smart.proxies.Asset;
import smart.proxies.Variable;
import smart.proxies.SyncMetadata;
import smart.proxies.SyncStatus;
import smart.proxies.MetricType;
import smart.proxies.EnergyType;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.HashSet;
import java.util.Date;
import java.lang.Boolean;
import java.util.regex.Pattern;
import java.util.regex.Matcher;
import java.util.HashMap;
import java.util.Map;
import com.mendix.systemwideinterfaces.core.UserAction;

public class SyncIIHVariables extends CustomJavaAction<IMendixObject>
{
	/** @deprecated use syncMetadata.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __syncMetadata;
	private final smart.proxies.SyncMetadata syncMetadata;
	private final java.lang.Boolean isScheduledMode;
	private final java.lang.Long BATCH_SIZE;
	private final java.lang.Boolean testLocal;

	public SyncIIHVariables(
		IContext context,
		IMendixObject _syncMetadata,
		java.lang.Boolean _isScheduledMode,
		java.lang.Long _bATCH_SIZE,
		java.lang.Boolean _testLocal
	)
	{
		super(context);
		this.__syncMetadata = _syncMetadata;
		this.syncMetadata = _syncMetadata == null ? null : smart.proxies.SyncMetadata.initialize(getContext(), _syncMetadata);
		this.isScheduledMode = _isScheduledMode;
		this.BATCH_SIZE = _bATCH_SIZE;
		this.testLocal = _testLocal;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext ctx = getContext();
		
		// === NETTOYAGE DES VARIABLES AVANT SYNCHRO ===
		cleanupVariables(ctx);
		getLogger().info("🧹 Nettoyage initial : anciennes Variables supprimées");
		
		getLogger().info("=== SYNCHRONISATION VARIABLES IIH ===");
		getLogger().info("⚙️ Mode: " + (isScheduledMode ? "Batch" : "Temps réel"));
		getLogger().info("📦 Batch size: " + BATCH_SIZE);
		getLogger().info("🌐 URL IIH: http://localhost:4203");

		// ✅ STRATÉGIE SIMPLIFIÉE - Pas de vérification des assets IIH
		// On utilise directement les assets Smart créés par ProcessIIHAssetTree
		getLogger().info("🎯 Stratégie: Utilisation des assets Smart existants pour récupérer les variables");
		
		// Pas de vérification des assets IIH - on fait confiance aux assets Smart
		// if (iihAssetsCount == 0) { ... } - SUPPRIMÉ

		VariableStats stats = new VariableStats();
		List<IMendixObject> buffer = new ArrayList<>();
		long startTime = System.currentTimeMillis();

		try {
			// Récupérer tous les assets Smart (sauf root avec IIH_Id = "0")
			List<Asset> smartAssets = getSmartAssetsExcludingRoot(ctx);
			getLogger().info("🎯 Assets Smart à traiter: " + smartAssets.size());
			
			if (smartAssets.isEmpty()) {
				getLogger().warn("⚠️ Aucun asset Smart trouvé ! Vérifiez que la sync Assets a bien fonctionné");
				return syncMetadata != null ? syncMetadata.getMendixObject() : null;
			}

			// LOG: Échantillon d'assets à traiter
			getLogger().info("📋 Premiers assets à traiter:");
			for (int i = 0; i < Math.min(5, smartAssets.size()); i++) {
				Asset asset = smartAssets.get(i);
				getLogger().info("   - " + asset.getIIH_Id() + " (" + asset.getNom() + ")");
			}
			if (smartAssets.size() > 5) {
				getLogger().info("   ... et " + (smartAssets.size() - 5) + " autres");
			}

			/* ------------- DEBUG - AJOUTER CETTE MÉTHODE TEMPORAIRE ------------- */
			// debugVariableMapping(ctx, stats);

			// Traiter chaque asset
			for (Asset asset : smartAssets) {
				try {
					processAssetVariables(ctx, asset, buffer, stats);
					
					// Progress reporting
					if (isScheduledMode && stats.assetsProcessed % 5 == 0) {
						double progress = (double) stats.assetsProcessed / smartAssets.size() * 100;
						getLogger().info("📊 Progress: " + stats.assetsProcessed + "/" + smartAssets.size() + 
										" (" + String.format("%.1f", progress) + "%) - " + 
										stats.variablesProcessed + " variables, " + 
										stats.iihApiCalls + " API calls");
					}
					
				} catch (Exception e) {
					stats.errors++;
					getLogger().error("❌ Erreur asset " + asset.getIIH_Id() + ": " + e.getMessage());
					// Continuer avec les autres assets
				}
			}

			// Commit final
			if (!buffer.isEmpty()) {
				getLogger().info("📦 Final commit en cours: " + buffer.size() + " variables...");
				Core.commitWithoutEvents(ctx, buffer);
				stats.variablesCommitted += buffer.size();
				getLogger().info("✅ Final commit terminé: " + buffer.size() + " variables");
			}

			// 🆕 Mise à jour des flags énergie sur les assets
			batchUpdateAssetEnergyFlags(ctx, stats);

			// Mettre à jour les métadonnées
			long duration = System.currentTimeMillis() - startTime;
			updateSyncMetadata(ctx, stats, duration, null);

		} catch (Exception e) {
			long duration = System.currentTimeMillis() - startTime;
			getLogger().error("💥 Erreur critique sync variables: " + e.getMessage(), e);
			updateSyncMetadata(ctx, stats, duration, e);
			throw e;
		}

		// Logs finaux
		logFinalVariableStats(stats, System.currentTimeMillis() - startTime);
		
		return syncMetadata != null ? syncMetadata.getMendixObject() : null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SyncIIHVariables";
	}

	// BEGIN EXTRA CODE
	/* ==== LOGGER ==== */
	private static final ILogNode LOG = Core.getLogger("IIHVariableSync");
	
	// 🐛 DEBUG - Flag pour contrôler les logs de debug 
	// UTILISATION :
	// 1. Laisser à TRUE pour diagnostiquer le problème EnergyType
	// 2. Examiner les logs générés pour comprendre pourquoi 'électricité' n'est pas reconnu  
	// 3. Une fois le problème résolu, mettre à FALSE pour retirer les logs
	private static final boolean DEBUG_ENERGY_PARSING = true;

	// ➕ NEW: regex pour extraire <metric>_<energy> (ex: consommation_elec)
	private static final Pattern VAR_REGEX = Pattern.compile("(?i)^([a-z0-9éèêà_]+)_([a-z]+)$");

	private ILogNode getLogger() {
		return LOG;
	}
	
	// 🐛 DEBUG Helper - Log conditionnel pour debug parsing
	private void debugLog(String message) {
		if (DEBUG_ENERGY_PARSING) {
			getLogger().info(message);
		}
	}

	/* ==== STATISTIQUES VARIABLES ==== */
	private static class VariableStats {
		int assetsProcessed = 0;
		int variablesProcessed = 0;
		int variablesCreated = 0;
		int variablesUpdated = 0;
		int variablesCommitted = 0;
		int iihApiCalls = 0;
		int errors = 0;
		
		// ✅ AJOUT - Cache pour optimiser les appels API
		private List<iihessentialsconnector.proxies.Variable> cachedAllVariables = null;
		private boolean apiCallMade = false;
		// 🆕 cache des flags énergie par asset
		private Map<String, AssetFlags> assetFlags = new HashMap<>();
	}

	// 🆕 Structure interne pour stocker les flags énergie d'un asset
	private static class AssetFlags {
		boolean elec = false;
		boolean gaz  = false;
		boolean eau  = false;
		boolean air  = false;
	}

	// 🆕 Résultat du parsing d'un nom de variable
	private static class ParseResult {
		MetricType metricType;
		EnergyType energyType;
		
		ParseResult(MetricType metric, EnergyType energy) {
			this.metricType = metric;
			this.energyType = energy;
		}
	}

	// 🆕 Helper pour récupérer ou créer le cache de flags d'un asset
	private AssetFlags getAssetFlags(VariableStats stats, Asset asset) {
		return stats.assetFlags.computeIfAbsent(asset.getIIH_Id(), k -> new AssetFlags());
	}

	/* ------------- RÉCUPÉRER ASSETS SMART - VERSION CORRIGÉE ------------- */
	private List<Asset> getSmartAssetsExcludingRoot(IContext ctx) throws Exception {
	    
	    // ✅ Récupérer TOUS les assets Smart
	    List<IMendixObject> assetObjects = Core.retrieveXPathQuery(ctx, "//Smart.Asset");
	    
	    List<Asset> assets = new ArrayList<>();
	    getLogger().info("📊 " + assetObjects.size() + " assets Smart trouvés au total");
	    
	    for (IMendixObject assetObj : assetObjects) {
	        Asset asset = Asset.initialize(ctx, assetObj);
	        
	        String iihId = asset.getIIH_Id();
	        String nom = asset.getNom();
	        
	        // ✅ DEBUG - Log de chaque asset pour comprendre le filtrage
	        getLogger().info("🔍 Asset trouvé: '" + nom + "' | IIH_Id: '" + iihId + "'");
	        
	        // ✅ CORRECTION - Filtrer UNIQUEMENT les assets root (IIH_Id = "0")
	        if (iihId != null && !"0".equals(iihId) && !iihId.trim().isEmpty()) {
	            
	            // ✅ SUPPRESSION du filtre sur le parent - Garder TOUS les assets non-root
	            assets.add(asset);
	            getLogger().info("   ✅ Asset ajouté: " + nom + " (" + iihId + ")");
	            
	            /* ANCIEN CODE PROBLÉMATIQUE :
	            try {
	                Asset parent = asset.getAsset_Parent();
	                if (parent != null) {
	                    assets.add(asset);
	                }
	            } catch (Exception e) {
	                if (!"0".equals(asset.getIIH_Id())) {
	                    assets.add(asset);
	                }
	            }
	            */
	        } else {
	            getLogger().info("   ❌ Asset exclu (root): " + nom + " (" + iihId + ")");
	        }
	    }
	    
	    getLogger().info("📊 " + assets.size() + " assets Smart sélectionnés (root exclu)");
	    
	    // ✅ DEBUG - Liste finale des assets sélectionnés
	    getLogger().info("📋 Assets Smart sélectionnés:");
	    for (Asset asset : assets) {
	        getLogger().info("   📄 " + asset.getNom() + " (" + asset.getIIH_Id() + ")");
	    }
	    
	    return assets;
	}

	/* ------------- TRAITER VARIABLES D'UN ASSET ------------- */
	private void processAssetVariables(IContext ctx, Asset asset, List<IMendixObject> buffer, 
									   VariableStats stats) throws Exception {
		
		stats.assetsProcessed++;
		String assetId = asset.getIIH_Id();
		String assetName = asset.getNom();
		
		getLogger().info("🔄 [" + stats.assetsProcessed + "] Traitement variables pour: " + 
						assetId + " (" + assetName + ")");

		try {
			// Appeler l'API IIH pour récupérer les variables de cet asset
			List<iihessentialsconnector.proxies.Variable> iihVariables = 
				loadVariablesFromIIH(ctx, assetId, stats);

			if (iihVariables.isEmpty()) {
				getLogger().debug("   📄 Aucune variable pour asset: " + assetName);
				return;
			}

			getLogger().info("   ✅ " + iihVariables.size() + " variables trouvées pour: " + assetName);

			// Traiter chaque variable
			for (iihessentialsconnector.proxies.Variable iihVar : iihVariables) {
				try {
					processVariable(ctx, iihVar, asset, buffer, stats);
				} catch (Exception e) {
					stats.errors++;
					String varName = iihVar != null ? iihVar.getVariableName() : "null";
					getLogger().error("❌ Erreur variable " + varName + 
									" (asset " + assetName + "): " + e.getMessage());
				}
			}
			
			getLogger().debug("   ✅ Variables traitées pour: " + assetName);

		} catch (Exception e) {
			stats.errors++;
			getLogger().error("❌ Erreur globale asset " + assetName + ": " + e.getMessage(), e);
		}
	}

	/* ------------- MÉTHODE loadVariablesFromIIH - DEBUG FINAL ------------- */
	private List<iihessentialsconnector.proxies.Variable> loadVariablesFromIIH(
	        IContext ctx, String assetId, VariableStats stats) throws Exception {
	    try {
	        if (!stats.apiCallMade) {
	            stats.iihApiCalls++;
	            stats.apiCallMade = true;
	            getLogger().info("🌐 Appel API Variables (récupération complète sans filtrage)");
	            String iihUrl = (testLocal != null && testLocal) ? "http://localhost:4203" : null;
	            getLogger().debug("🌐 URL IIH utilisée: " + iihUrl);
	            IMendixObject resultObject = (IMendixObject) Core.microflowCall("IIHEssentialsConnector.GET_v1_8_Variables_All")
	                .withParam("IIHEssentialsURL_RequiredIfExternal", iihUrl)
	                .withParam("DecryptedDeviceToken_RequiredIfExternal", (String) null)
	                .withParam("AspectList_Optional", (List<iihessentialsconnector.proxies.Aspect>) null)
	                .withParam("VariableList_Optional", (List<iihessentialsconnector.proxies.Variable>) null)
	                .withParam("AssetList_Optional", (List<iihessentialsconnector.proxies.Asset>) null)
	                .withParam("AdapterList_Optional", (List<iihessentialsconnector.proxies.Adapter>) null)
	                .execute(ctx);
	            stats.cachedAllVariables = new ArrayList<>();
	            if (resultObject != null) {
	                iihessentialsconnector.proxies.VariablesMessage result = 
	                    iihessentialsconnector.proxies.VariablesMessage.initialize(ctx, resultObject);
	                List<IMendixObject> allVariableObjects = Core.retrieveByPath(ctx, result.getMendixObject(), 
	                    "IIHEssentialsConnector.Variable_VariablesMessage");
	                getLogger().info("📊 " + allVariableObjects.size() + " variables totales récupérées depuis l'API");
	                for (IMendixObject varObj : allVariableObjects) {
	                    iihessentialsconnector.proxies.Variable iihVar = 
	                        iihessentialsconnector.proxies.Variable.initialize(ctx, varObj);
	                    // DEBUG FINAL - Log structure complète
	                    String objectId = iihVar.getObjectId();
	                    String variableName = iihVar.getVariableName();
	                    String assetIdVar = iihVar.getAssetId();
	                    String dataType = iihVar.getDataType();
	                    String unit = iihVar.getUnit();
	                    String topic = iihVar.getTopic();
	                    String aspectId = iihVar.getAspectId();
	                    String aspectName = iihVar.getAspectName();
	                    String adapterId = iihVar.getAdapterId();
	                    Boolean connected = iihVar.getConnected();
	                    Boolean store = iihVar.getStore();
	                    getLogger().info("🔍 === VARIABLE IIH COMPLÈTE ===");
	                    getLogger().info("   🆔 ObjectId (ID UNIQUE): '" + objectId + "'");
	                    getLogger().info("   📛 VariableName (NOM): '" + variableName + "'");
	                    getLogger().info("   🏢 AssetId: '" + assetIdVar + "'");
	                    getLogger().info("   📊 DataType: '" + dataType + "'");
	                    getLogger().info("   📏 Unit: '" + unit + "'");
	                    getLogger().info("   📡 Topic: '" + topic + "'");
	                    getLogger().info("   🎯 AspectId: '" + aspectId + "'");
	                    getLogger().info("   🏷️ AspectName: '" + aspectName + "'");
	                    getLogger().info("   🔌 AdapterId: '" + adapterId + "'");
	                    getLogger().info("   ✅ Connected: " + connected);
	                    getLogger().info("   💾 Store: " + store);
	                    stats.cachedAllVariables.add(iihVar);
	                }
	                getLogger().info("📊 " + stats.cachedAllVariables.size() + " variables totales mises en cache (sans filtrage)");
	            } else {
	                getLogger().warn("⚠️ Réponse API null - cache vide");
	            }
	        }
	        List<iihessentialsconnector.proxies.Variable> variables = new ArrayList<>();
	        if (stats.cachedAllVariables != null) {
	            getLogger().info("🔍 Recherche de variables pour asset: '" + assetId + "'");
	            for (iihessentialsconnector.proxies.Variable iihVar : stats.cachedAllVariables) {
	                String varAssetId = iihVar.getAssetId();
	                String varName = iihVar.getVariableName();
	                getLogger().debug("   🔍 Comparaison: AssetId demandé='" + assetId + "' vs Variable AssetId='" + varAssetId + "'");
	                boolean isMatch = false;
	                if (assetId.equals(varAssetId)) {
	                    isMatch = true;
	                    getLogger().info("   ✅ MATCH EXACT: " + varName + " (AssetId: " + varAssetId + ")");
	                }
	                else if (varAssetId != null && assetId.equalsIgnoreCase(varAssetId)) {
	                    isMatch = true;
	                    getLogger().info("   ✅ MATCH CASSE: " + varName + " (AssetId: " + varAssetId + ")");
	                }
	                else if (varAssetId != null && (assetId.startsWith(varAssetId) || varAssetId.startsWith(assetId))) {
	                    isMatch = true;
	                    getLogger().info("   ✅ MATCH PARTIEL: " + varName + " (AssetId: " + varAssetId + ")");
	                }
	                if (isMatch) {
	                    variables.add(iihVar);
	                }
	            }
	        }
	        getLogger().info("✅ " + variables.size() + " variables trouvées pour asset: " + assetId);
	        return variables;
	    } catch (Exception e) {
	        stats.errors++;
	        getLogger().error("❌ Erreur API Variables pour asset " + assetId + ": " + e.getMessage(), e);
	        if (e.getMessage() != null && 
	            (e.getMessage().contains("Connection") || e.getMessage().contains("timeout"))) {
	            getLogger().error("🌐 Problème de connexion à IIH - Vérifiez que http://localhost:4203 est accessible");
	        }
	        return new ArrayList<>();
	    }
	}

	/* ------------- PROCESSVARIABLE – VERSION ENUM-READY ------------- */
	private void processVariable(IContext ctx,
								 iihessentialsconnector.proxies.Variable iihVar,
								 Asset asset,
								 List<IMendixObject> buffer,
								 VariableStats stats) throws Exception {

		stats.variablesProcessed++;

		String varId   = iihVar.getObjectId();
		String varName = iihVar.getVariableName();
		String unit    = iihVar.getUnit();
		String dataType = iihVar.getDataType();

		if (varId == null || varId.isBlank()) {
			getLogger().warn("⚠️ Variable sans ObjectId ignorée – asset " + asset.getIIH_Id());
			stats.variablesProcessed--; // on ne la compte pas
			return;
		}

		// === NEW : parse enums à partir du nom (version plus permissive)
		MetricType metricType = MetricType.Custom;
		EnergyType energyType = EnergyType.None;

		// 🐛 DEBUG - Log détaillé du parsing des noms
		debugLog("🔍 === DEBUG PARSING VARIABLE ===");
		debugLog("🔍 Variable name: '" + varName + "'");

		if (varName != null && !varName.isBlank()) {
			String lowerName = varName.toLowerCase();
			debugLog("🔍 Lowercase name: '" + lowerName + "'");
			
			// 🆕 PARSING INTELLIGENT - Gérer les patterns complexes
			ParseResult result = parseVariableName(lowerName);
			metricType = result.metricType;
			energyType = result.energyType;
			
			debugLog("🔍 Final MetricType: " + metricType);
			debugLog("🔍 Final EnergyType: " + energyType);
		} else {
			debugLog("🔍 Variable name is null or blank");
		}
		debugLog("🔍 === END DEBUG PARSING ===");

		/* === Recherche / upsert identique à la logique d'origine === */
		Variable smartVar = null;
		boolean isNew = true;

		List<IMendixObject> found = Core.retrieveXPathQuery(ctx,
			"//Smart.Variable[IIH_Id='" + varId + "']");
		if (!found.isEmpty()) {
			smartVar = Variable.initialize(ctx, found.get(0));
			isNew = false;
		} else {
			smartVar = new Variable(ctx);
		}

		if (isNew) stats.variablesCreated++; else stats.variablesUpdated++;

		// === mapping des champs (ajout enums)
		smartVar.setIIH_Id(varId);
		smartVar.setName(varName != null ? varName : "");
		smartVar.setUnit(unit != null ? unit : "");
		smartVar.setDataType(dataType != null ? dataType : "");
		smartVar.setIsActive(true);
		smartVar.setLastSyncDate(new Date());
		smartVar.setVariable_Asset(asset);

		// === NEW : setters enum
		smartVar.setMetricType(metricType);
		smartVar.setEnergyType(energyType);

		// 🆕 Taggage des flags énergie dans le cache
		AssetFlags flags = getAssetFlags(stats, asset);
		switch (energyType) {
			case Elec:
				flags.elec = true;
				break;
			case Gaz:
				flags.gaz = true;
				break;
			case Eau:
				flags.eau = true;
				break;
			case Air:
				flags.air = true;
				break;
			default:
				// no-op
				break;
		}

		buffer.add(smartVar.getMendixObject());

		if (buffer.size() >= BATCH_SIZE) {
			Core.commitWithoutEvents(ctx, buffer);
			stats.variablesCommitted += buffer.size();
			buffer.clear();
		}
	}

	/* === NEW : helpers enum ------------------------------------------------ */

	private MetricType mapMetric(String raw) {
		if (raw == null) return MetricType.Custom;
		switch (raw.toLowerCase()) {
			case "consommation":
			case "conso":
				return MetricType.Conso;
			case "ipe_kg":
			case "ipekg":
				return MetricType.IPE_kg;
			case "ipe":
				return MetricType.IPE;
			case "production":
			case "prod":
				return MetricType.Prod;
			case "production_kg":
			case "prod_kg":
				return MetricType.Prod_kg;
			default:
				return MetricType.Custom;
		}
	}

	private EnergyType mapEnergy(String raw) {
		if (raw == null) return EnergyType.None;
		
		// 🐛 DEBUG - Log pour diagnostiquer le problème de reconnaissance
		debugLog("🔍 DEBUG mapEnergy - Raw input: '" + raw + "' (length: " + raw.length() + ")");
		
		// Normaliser et nettoyer la chaîne pour une comparaison robuste
		String normalized = raw.toLowerCase()
			.trim()
			.replace("é", "e")
			.replace("è", "e") 
			.replace("ê", "e")
			.replace("à", "a")
			.replace("ç", "c");
		
		debugLog("🔍 DEBUG mapEnergy - Normalized: '" + normalized + "'");
		
		// Électricité : vérifier si la chaîne commence par "elec" ou "electricite"
		if (normalized.startsWith("elec") || normalized.startsWith("electricite")) {
			debugLog("✅ DEBUG mapEnergy - Matched ELEC for: '" + raw + "'");
			return EnergyType.Elec;
		}
		
		// Gaz : vérifier si la chaîne commence par "gaz" ou "gas"
		if (normalized.startsWith("gaz") || normalized.startsWith("gas")) {
			debugLog("✅ DEBUG mapEnergy - Matched GAZ for: '" + raw + "'");
			return EnergyType.Gaz;
		}
		
		// Eau : vérifier si la chaîne commence par "eau" ou "water"
		if (normalized.startsWith("eau") || normalized.startsWith("water")) {
			debugLog("✅ DEBUG mapEnergy - Matched EAU for: '" + raw + "'");
			return EnergyType.Eau;
		}
		
		// Air : vérifier si la chaîne commence par "air"
		if (normalized.startsWith("air")) {
			debugLog("✅ DEBUG mapEnergy - Matched AIR for: '" + raw + "'");
			return EnergyType.Air;
		}
		
		debugLog("⚠️ DEBUG mapEnergy - No match found for: '" + raw + "' - returning None");
		return EnergyType.None;
	}

	// 🆕 PARSING INTELLIGENT des noms de variables
	private ParseResult parseVariableName(String lowerName) {
		debugLog("🔍 parseVariableName - Input: '" + lowerName + "'");
		
		// === PATTERNS SPÉCIAUX - Priorité haute ===
		
		// 1. Production_kg → MetricType.Prod_kg + EnergyType.None
		if (lowerName.startsWith("production_kg")) {
			debugLog("✅ Matched pattern: Production_kg");
			return new ParseResult(MetricType.Prod_kg, EnergyType.None);
		}
		
		// 2. IPE_kg_xxx → MetricType.IPE_kg + EnergyType correspondant
		if (lowerName.startsWith("ipe_kg_")) {
			String energyPart = lowerName.substring("ipe_kg_".length());
			debugLog("✅ Matched pattern: IPE_kg_xxx, energyPart: '" + energyPart + "'");
			EnergyType energy = mapEnergy(energyPart);
			return new ParseResult(MetricType.IPE_kg, energy);
		}
		
		// 3. IPE_xxx → MetricType.IPE + EnergyType correspondant  
		if (lowerName.startsWith("ipe_") && !lowerName.startsWith("ipe_kg_")) {
			String energyPart = lowerName.substring("ipe_".length());
			debugLog("✅ Matched pattern: IPE_xxx, energyPart: '" + energyPart + "'");
			EnergyType energy = mapEnergy(energyPart);
			return new ParseResult(MetricType.IPE, energy);
		}
		
		// === PARSING GÉNÉRIQUE - Token splitting ===
		String[] tokens = lowerName.split("[_\\-\\.]+");
		
		debugLog("🔍 Generic parsing - Tokens:");
		for (int i = 0; i < tokens.length; i++) {
			debugLog("   tokens[" + i + "] = '" + tokens[i] + "'");
		}
		
		String metricRaw = tokens.length > 0 ? tokens[0] : null;
		String energyRaw = tokens.length > 1 ? tokens[1] : null;
		
		debugLog("🔍 Generic parsing - metricRaw: '" + metricRaw + "', energyRaw: '" + energyRaw + "'");
		
		// 4. Cas spéciaux avec tokens multiples
		if (tokens.length >= 2) {
			// production_kg avec token split
			if ("production".equals(metricRaw) && "kg".equals(energyRaw)) {
				debugLog("✅ Matched tokens: production + kg");
				return new ParseResult(MetricType.Prod_kg, EnergyType.None);
			}
			
			// ipe_kg avec token split  
			if ("ipe".equals(metricRaw) && "kg".equals(energyRaw) && tokens.length > 2) {
				String energyPart = tokens[2];
				debugLog("✅ Matched tokens: ipe + kg + energy, energyPart: '" + energyPart + "'");
				EnergyType energy = mapEnergy(energyPart);
				return new ParseResult(MetricType.IPE_kg, energy);
			}
		}
		
		// 5. Parsing standard metric + energy
		MetricType metric = mapMetric(metricRaw);
		EnergyType energy = mapEnergy(energyRaw);
		
		debugLog("🔍 Generic result - MetricType: " + metric + ", EnergyType: " + energy);
		return new ParseResult(metric, energy);
	}

	/* ------------- METTRE À JOUR MÉTADONNÉES SYNC ------------- */
	private void updateSyncMetadata(IContext ctx, VariableStats stats, long durationMs, Exception error) throws Exception {
		
		if (syncMetadata != null) {
			syncMetadata.setVariablesProcessed(stats.variablesProcessed);
			syncMetadata.setVariablesCreated(stats.variablesCreated);
			syncMetadata.setVariablesUpdated(stats.variablesUpdated);
			
			// Mettre à jour le statut si erreur
			if (error != null && syncMetadata.getSyncStatus() != SyncStatus.Error) {
				syncMetadata.setSyncStatus(SyncStatus.Error);
				syncMetadata.setErrorMessage(error.getMessage());
			}
			
			Core.commitWithoutEvents(ctx, syncMetadata.getMendixObject());
		}
	}

	/* ------------- LOGS FINAUX ------------- */
	private void logFinalVariableStats(VariableStats stats, long durationMs) {
		getLogger().info("=== STATISTIQUES VARIABLES FINALES ===");
		getLogger().info("⏱️ Durée totale: " + durationMs + "ms (" + String.format("%.2f", durationMs/1000.0) + "s)");
		getLogger().info("🏢 Assets traités: " + stats.assetsProcessed);
		getLogger().info("📊 Variables traitées: " + stats.variablesProcessed);
		getLogger().info("✨ Variables créées: " + stats.variablesCreated);
		getLogger().info("🔄 Variables mises à jour: " + stats.variablesUpdated);
		getLogger().info("💾 Variables committées: " + stats.variablesCommitted);
		getLogger().info("🌐 Appels API IIH: " + stats.iihApiCalls);
		getLogger().info("❌ Erreurs rencontrées: " + stats.errors);
		
		if (stats.variablesProcessed > 0) {
			double avgTimePerVar = (double) durationMs / stats.variablesProcessed;
			getLogger().info("📈 Temps moyen par variable: " + String.format("%.2f", avgTimePerVar) + "ms");
		}
		
		getLogger().info("=== FIN SYNC VARIABLES ===");
	}

	/* ------------- NETTOYAGE VARIABLES ------------- */
	private void cleanupVariables(IContext ctx) throws Exception {
		List<IMendixObject> variables = Core.retrieveXPathQuery(ctx, "//Smart.Variable");
		if (!variables.isEmpty()) {
			Core.deleteWithoutEvents(ctx, variables, false);
			getLogger().info("🗑️  " + variables.size() + " Variables supprimées");
		}
	}

	// 🆕 Mise à jour batch des flags énergie sur les assets Smart
	private void batchUpdateAssetEnergyFlags(IContext ctx, VariableStats stats) throws Exception {
		List<IMendixObject> toCommit = new ArrayList<>();

		for (Map.Entry<String, AssetFlags> entry : stats.assetFlags.entrySet()) {
			String iihId      = entry.getKey();
			AssetFlags flags  = entry.getValue();

			List<IMendixObject> found = Core.retrieveXPathQuery(ctx,
				"//Smart.Asset[IIH_Id='" + iihId + "']");
			if (found.isEmpty()) continue;

			Asset a = Asset.initialize(ctx, found.get(0));
			boolean dirty = false;

			if (flags.elec && !Boolean.TRUE.equals(a.getisElec())) { a.setisElec(true); dirty = true; }
			if (flags.gaz  && !Boolean.TRUE.equals(a.getisGaz()))  { a.setisGaz(true);  dirty = true; }
			if (flags.eau  && !Boolean.TRUE.equals(a.getisEau()))  { a.setisEau(true);  dirty = true; }
			if (flags.air  && !Boolean.TRUE.equals(a.getisAir()))  { a.setisAir(true);  dirty = true; }

			if (dirty) toCommit.add(a.getMendixObject());
		}

		if (!toCommit.isEmpty()) {
			Core.commitWithoutEvents(ctx, toCommit);
			getLogger().info("⚡️ Asset energy flags mis à jour pour " + toCommit.size() + " assets");
		} else {
			getLogger().info("👌 Aucun changement de flags énergie à committer");
		}
	}
	// END EXTRA CODE
}
